Filtering Repeated Wildcards Enhances Regular Expression Performance
opensearch-project/OpenSearch pull request #10180
Opened 2023-09-22 09:36 UTC by dormanze

### Description
This modification avoids meaningless recursive calls caused by continuous use of the wildcard [*]. Try to skip consecutive wildcards [*].

### Related Issues

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-22 12:23 UTC, dormanze commented
> ### Gradle Check (Jenkins) Run Completed with:
> * **RESULT:** FAILURE ❌
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/26109/
> * **CommitID:** [0ae7d66](https://github.com/opensearch-project/OpenSearch/commit/0ae7d66fb1c99087a065dd285392dc385cb6c606)
>   Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green.
>   Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

This failure doesn't seem to be related to the code I submitted.

2023-09-22 12:26 UTC, peternied reviewed
Thanks for the change with test case.  Since you mentioned improve performance could you see about adding a benchmark and producing before / after numbers?

2023-09-23 01:14 UTC, xiaoyuan0821 commented
> Thanks for the change with test case. Since you mentioned improve performance could you see about adding a benchmark and producing before / after numbers?

Actually this is a fix for the DOS flaw https://github.com/opensearch-project/OpenSearch/issues/10120

2023-09-23 02:15 UTC, dormanze commented
> Thanks for the change with test case. Since you mentioned improve performance could you see about adding a benchmark and producing before / after numbers?

Thank you for your reply.
As @xiaoyuan0821 said, this pr is mainly designed to repair CVE-2023-31419. 
If the number of consecutive special characters [*] exceeds 20,000, the stack may overflows on the server.
The optimization aims to reduce the number of recursions. The improvement of query performance is not obvious because the recursive method [simpleMatchWithNormalizedStrings](https://github.com/opensearch-project/OpenSearch/blob/9e906714ebfd2c1a89d6249362fe1cc1cff4c548/server/src/main/java/org/opensearch/common/regex/Regex.java#L131C51-L131C51) is not time-consuming.

2023-09-28 19:15 UTC, dblock requested changes
This looks identical to https://github.com/elastic/elasticsearch/pull/98176. We cannot accept non-APLv2 code unfortunately.

2023-10-07 02:18 UTC, closed without merging