Backport Performance Improvement for Datetime testing to 2.x
opensearch-project/OpenSearch pull request #10448
Opened 2023-10-06 06:03 UTC by CaptainDredge

### Description
Backport changes #9567 and #10385

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/4558

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-06 08:49 UTC, CaptainDredge commented
@reta , @dblock can we go ahead and merge the backport targeting  `v2.11`? The whole change is under featureflag so by any small chance we face any regression intermittently we could turn it off and I could push any required fix, although I'm confident of the change

2023-10-06 12:15 UTC, CaptainDredge commented
corresponding 2.11 backport
**https://github.com/opensearch-project/OpenSearch/pull/10453**

2023-10-06 13:11 UTC, reta commented on server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
> +import java.util.concurrent.CopyOnWriteArrayList;
Should be gone, right?

2023-10-06 14:22 UTC, CaptainDredge commented on server/src/main/java/org/opensearch/search/DocValueFormat.java
> +            if (in.getVersion().onOrAfter(Version.V_2_11_0)) {
Sure, waiting for #10458 to go in. Will rebase then

2023-10-06 14:23 UTC, CaptainDredge commented on server/src/main/java/org/opensearch/common/time/JavaDateFormatter.java
> +import java.util.concurrent.CopyOnWriteArrayList;
Yup this was a miss

2023-10-06 15:24 UTC, dblock approved these changes

2023-10-06 15:34 UTC, reta commented on server/src/main/java/org/opensearch/search/DocValueFormat.java
> +            if (in.getVersion().onOrAfter(Version.V_2_11_0)) {
Good to go with 2.12, @CaptainDredge !

2023-10-06 15:39 UTC, CaptainDredge commented on server/src/main/java/org/opensearch/search/DocValueFormat.java
> +            if (in.getVersion().onOrAfter(Version.V_2_11_0)) {
Sad I couldn't make it to 2.11 😞

2023-10-06 15:40 UTC, CaptainDredge commented
After DB approval I just included reta's suggestion of removing `CopyOnWriteList` and rebased on `2.x`

2023-10-06 15:41 UTC, dblock approved these changes

2023-10-06 16:59 UTC, CaptainDredge commented
Flaky tests are failing 😞

2023-10-06 18:04 UTC, dblock commented
> Flaky tests are failing 😞

Please take the time to extract the failures from logs and add links to the already opened GitHub issues on those tests. That helps raise awareness of how often they fail and where.

2023-10-06 22:16 UTC, sohami commented
@CaptainDredge There are multiple failures for date time format failures across different tests and these are happening recently which looks related to your PR. Can you check once and confirm, I have shared the tests here: https://github.com/opensearch-project/OpenSearch/pull/9567#issuecomment-1751454852

Also the gradle check failures are in mixed cluster tests again related to date timestamp. It does look like this change has some missing cases or causing regression.

```
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/90_search_after/date}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_90_search_after_date_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/230_composite/date_histogram with time_zone}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_230_composite_date_histogram_with_time_zone_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/370_multi_terms/Date test}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_370_multi_terms_Date_test_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/330_auto_date_histogram/basic}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_330_auto_date_histogram_basic_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/330_distributed_sort/test distributed sort can rewrite query to match no docs}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_330_distributed_sort_test_distributed_sort_can_rewrite_query_to_match_no_docs_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/date histogram aggregation with date and date_nanos mapping}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_date_histogram_aggregation_with_date_and_date_nanos_mapping_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/330_auto_date_histogram/avg_bucket}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_330_auto_date_histogram_avg_bucket_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/300_pipeline/deep cumulative sum}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_300_pipeline_deep_cumulative_sum_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/240_max_buckets/Max bucket}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_240_max_buckets_Max_bucket_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/10_histogram/Deprecated _time order}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_10_histogram_Deprecated__time_order_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/230_composite/date_histogram on date_nanos}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_230_composite_date_histogram_on_date_nanos_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/280_rare_terms/Date test}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_280_rare_terms_Date_test_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/90_search_after/date_nanos}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_90_search_after_date_nanos_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/10_histogram/date_histogram on range with offset}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_10_histogram_date_histogram_on_range_with_offset_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/10_histogram/date_histogram}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_10_histogram_date_histogram_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/20_terms/Unmapped dates}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_20_terms_Unmapped_dates_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/10_histogram/date_histogram on range}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_10_histogram_date_histogram_on_range_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/40_range/Date range}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_40_range_Date_range_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/230_composite/Composite aggregation with date_histogram offset}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_230_composite_Composite_aggregation_with_date_histogram_offset_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search/240_date_nanos/test sorting against date_nanos only fields}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_240_date_nanos_test_sorting_against_date_nanos_only_fields_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/40_range/Date range unmapped with children}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_40_range_Date_range_unmapped_with_children_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/10_histogram/date_histogram with pre-epoch daylight savings time transition}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_aggregation_10_histogram_date_histogram_with_pre_epoch_daylight_savings_time_transition_/)
[org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT.test {p0=search.aggregation/310_date_agg_per_day_of_week/Date aggregation per day of week}](https://build.ci.opensearch.org/job/gradle-check/27341/testReport/junit/org.opensearch.backwards/MixedClusterClientYamlTestSuiteIT/test__p0_search_ [...]

2023-10-06 22:26 UTC, sohami commented
It seems like new change is supposed to be behind feature flag, however the default value of feature flag is `true`. See [here](https://github.com/opensearch-project/OpenSearch/pull/10448/files#diff-588ab69181acbbc72f7b46c083ae290bd363b71ff2300395b0a1648dcfe8eff3R122). So probably setting it to `false` will revert to original behavior. But still there looks to be some underlying issue on how this change is implemented.

2023-10-07 01:59 UTC, reta commented
> @CaptainDredge @dblock There are multiple failures for date time format failures across different tests and these are happening recently which looks related to your PR

@sohami replied you in other comment but should be fixed by https://github.com/opensearch-project/OpenSearch/pull/10385

2023-10-07 02:01 UTC, sohami commented
> > @CaptainDredge @dblock There are multiple failures for date time format failures across different tests and these are happening recently which looks related to your PR
> 
> @sohami replied you in other comment but should be fixed by #10385

Thanks @reta . However is it intentional to have the feature flag setting `true` by default for this change ?

2023-10-07 02:03 UTC, reta commented
> Thanks @reta . However is it intentional to have the feature flag setting true by default for this change ? See here

Yes, it was intentional (as pure optimization)

2023-10-07 02:15 UTC, sohami commented
> > Thanks @reta . However is it intentional to have the feature flag setting true by default for this change ? See here
> 
> Yes, it was intentional (as pure optimization)

@reta @CaptainDredge In that case, I think we should just ensure it is indeed fixing the test failures reported and resolve those issues. @CaptainDredge can you take care of that ?

2023-10-13 19:02 UTC, reta commented
> * **URL:** https://build.ci.opensearch.org/job/gradle-check/27842/

https://github.com/opensearch-project/OpenSearch/issues/10616

2023-10-16 14:07 UTC, reta approved these changes

2023-10-16 15:31 UTC, reta requested changes

2023-10-19 15:10 UTC, CaptainDredge commented on server/src/main/java/org/opensearch/search/DocValueFormat.java
> +            if (in.getVersion().onOrAfter(Version.V_2_11_0)) {
Thanks @reta . I was busy in oncall stuff since few days. Will take a look at what's missing in the implementation which is leading to test failures

2023-10-19 15:18 UTC, reta approved these changes

2023-10-19 15:21 UTC, reta commented on server/src/main/java/org/opensearch/search/DocValueFormat.java
> +            if (in.getVersion().onOrAfter(Version.V_2_11_0)) {
I think 2_11_0 -> 2.12_0 should fix it

2023-10-19 16:04 UTC, merged