Support index level allocation filtering for searchable snapshot index
opensearch-project/OpenSearch pull request #11563
Opened 2023-12-11 15:58 UTC by bugmakerrrrrr

### Description
Two changes here:
1. Support index level allocation filtering for searchable snapshot index: filter out the shards that cannot remain on the current node and prioritize moving them to eligible nodes before considering moving shards on excluded nodes;
2. Eliminate the logic of swapping primary with replica, as a shard cannot be transitioned from primary to replica mode.
https://github.com/opensearch-project/OpenSearch/blob/6bb53dea24264fc91dc46824041157066a16b74e/server/src/main/java/org/opensearch/index/shard/IndexShard.java#L604

### Related Issues
Resolves #11468

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [x] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-12-13 17:56 UTC, kotwanikunal commented
> Eliminate the logic of swapping primary with replica, as a shard cannot be transitioned from primary to replica mode
@bugmakerrrrrr In a writable, local index scenario - the swap from replica to primary is not possible. 
For a remote, read-only shard, this is possible in certain scenarios as we can "mark" the shard as primary or replica with a minor performance hit.

2023-12-15 12:21 UTC, bugmakerrrrrr commented
> > Eliminate the logic of swapping primary with replica, as a shard cannot be transitioned from primary to replica mode
> > @bugmakerrrrrr In a writable, local index scenario - the swap from replica to primary is not possible.
> > For a remote, read-only shard, this is possible in certain scenarios as we can "mark" the shard as primary or replica with a minor performance hit.

@kotwanikunal I know what you mean, but AFAIU, the cost of relocating a searchable snapshot index is very low, the only side effect is that target shard will experience a cold start. Swapping shards does indeed preserve the cache of the source shard. However, because the default search preference now is `_primary`, swapping shards has very limited effect on improving cold start.

Moreover, in the current implementation, swapping shards can cause the `IllegalArgumentException` (`illegal state: trying to move shard from primary mode to replica mode`). We can certainly skip specific checks for the searchable snapshot index, but I am not sure if this will cause other problems and make the code messy, so I tend to remove the logic of swapping shards.

2024-01-08 11:32 UTC, bugmakerrrrrr commented
@kotwanikunal Could you please have a look?

2024-01-09 05:41 UTC, kotwanikunal requested changes
Rest LGTM.

2024-01-09 05:41 UTC, kotwanikunal commented on server/src/main/java/org/opensearch/cluster/routing/allocation/allocator/RemoteShardsBalancer.java
> +        return !shard.started() || !RoutingPool.REMOTE_CAPABLE.equals(RoutingPool.getShardPool(shard, allocation));
The prevailing style is `shard.started() == false || RoutingPool.REMOTE_CAPABLE.equals(RoutingPool.getShardPool(shard, allocation) == false`

2024-01-09 13:22 UTC, bugmakerrrrrr commented
> Rest LGTM.

@kotwanikunal all relevant issues fixed

2024-01-17 23:13 UTC, andrross commented
I just pushed a rebase from main and fixed the conflict in the changelog

2024-01-18 18:24 UTC, kotwanikunal approved these changes

2024-01-18 18:25 UTC, merged