FIX: UOE While building Exists query for nested search_as_you_type field
opensearch-project/OpenSearch pull request #12048
Opened 2024-01-27 17:20 UTC by Luci-MG

### Description
FIX: Fixes UOE while building exists query for nested search_as_you_type field

### Related Issues
Resolves #[11821](https://github.com/opensearch-project/OpenSearch/issues/11821)

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

Signed-off-by: Mrudhul Guda <mg6.dev@gmail.com>

2024-02-01 03:04 UTC, owaiskazi19 requested changes
LGTM with few comments

2024-02-01 03:04 UTC, owaiskazi19 commented on modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
> +import org.apache.lucene.search.*;
Let's remove the wildcard imports

2024-02-01 03:04 UTC, owaiskazi19 commented on modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
> +        assertThat(actual, equalTo(expected));
Nit:
```suggestion
        assertEquals(expected, actual);
```

2024-02-01 03:04 UTC, owaiskazi19 commented on modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
> +import org.opensearch.index.query.*;
Here as well

2024-02-01 17:03 UTC, Luci-MG commented on modules/mapper-extras/src/test/java/org/opensearch/index/mapper/SearchAsYouTypeFieldMapperTests.java
> +import org.apache.lucene.search.*;
Sure!! sorry IDE auto optimized imports

2024-02-01 17:05 UTC, Luci-MG commented
> Thanks @Luci-MG. You need to rebase with latest `main` to resolve the conflicts. LGTM with few comments.

Hello @owaiskazi19  Refactored and committed the changes based on the review requests, Please re-review again
Thank you :)

2024-02-01 17:08 UTC, Luci-MG commented
> Thanks @Luci-MG. You need to rebase with latest `main` to resolve the conflicts. LGTM with few comments.

Hello @owaiskazi19 Refactored and committed the changes based on the review requests, Please re-review again
Thank you :)

2024-02-01 18:12 UTC, owaiskazi19 commented
@Luci-MG `:modules:mapper-extras:spotlessJavaCheck` failed. Can you run `./gradlew spotlessApply` and push again?

2024-02-01 18:24 UTC, Luci-MG commented
> @Luci-MG `:modules:mapper-extras:spotlessJavaCheck` failed. Can you run `./gradlew spotlessApply` and push again?

Done this and pushed the changes

2024-02-05 22:02 UTC, kkmr approved these changes

2024-02-05 22:43 UTC, owaiskazi19 approved these changes
LGTM! @msfroh can you take another look? Thanks

2024-02-07 23:24 UTC, owaiskazi19 commented
@Luci-MG can you resolve the conflicts?

2024-02-08 12:26 UTC, Luci-MG commented
Hello @owaiskazi19 Resolved the conflicts and rebased with the latest main

2024-02-08 20:45 UTC, msfroh commented
> LGTM! @msfroh can you take another look? Thanks

The change looks nice and simple. 

I'm trying to figure out why the `existsQuery` threw an exception. What I've been able to piece together is that the SearchAsYouTypeFieldMapper was added in 2019, while the base `existsQuery` implementation was added in 2020. So that probably explains it.

Then I'm thinking, what path will this `existsQuery` take now? AFAIK, it will never match anything, looking at the super-class implementation:
```
        if (hasDocValues()) {
            return new DocValuesFieldExistsQuery(name());
        } else if (getTextSearchInfo().hasNorms()) {
            return new NormsFieldExistsQuery(name());
        } else {
            return new TermQuery(new Term(FieldNamesFieldMapper.NAME, name()));
        }
```

The prefix field doesn't have doc values or norms, so it will go into that third path. I could be mistaken, but I think `<field_name>._index_prefix` (the name of the prefix field) doesn't get added to the field names field, because it's not a "real" field.

2024-02-08 20:48 UTC, msfroh commented
I think to me, the bigger question is **why** do we end up trying to call `existsQuery` on the prefix field type? I think there's a flaw in the logic somewhere else and the UOE is just highlighting that.

2024-02-08 22:01 UTC, msfroh commented
> I think to me, the bigger question is **why** do we end up trying to call `existsQuery` on the prefix field type? I think there's a flaw in the logic somewhere else and the UOE is just highlighting that.

Okay -- I was able to answer that by debugging the unit test that you added. (Thank you very much for that, by the way!)

I now understand that the issue comes from the outer object field (named `field`). Because it does not exist in the mapper service as a direct type, it tries iterating through all fields whose name starts with `field.*`, which includes the "virtual" fields, like the prefix and shingle fields. So far as I can tell, we would run into the same problem with a `text` field with `index_prefixes` enabled.

 I tried the following change to `newObjectFieldExistsQuery` to avoid generating queries for those "virtual" subfields:
 
 ```
    private static Query newObjectFieldExistsQuery(QueryShardContext context, String objField) {
        BooleanQuery.Builder booleanQuery = new BooleanQuery.Builder();
        Collection<String> fields = context.simpleMatchToIndexNames(objField + ".*");
        for (String field : fields) {
            int dotPos = field.lastIndexOf('.');
            if (dotPos > 0 && field.charAt(dotPos + 1) == '_') { // This is a subfield (e.g. prefix) of a complex field type. Skip it.
                continue;
            }
            Query existsQuery = context.getMapperService().fieldType(field).existsQuery(context);
            booleanQuery.add(existsQuery, Occur.SHOULD);
        }
        return new ConstantScoreQuery(booleanQuery.build());
    }
```

2024-03-13 16:20 UTC, msfroh commented
@Luci-MG  -- are you able to fix `newObjectFieldExistsQuery` instead? It looks like that's where the bug really resides.

2024-03-13 16:23 UTC, Luci-MG commented
> @Luci-MG -- are you able to fix `newObjectFieldExistsQuery` instead? It looks like that's where the bug really resides.

Hello @msfroh let me check that will update you

2024-03-13 18:32 UTC, Luci-MG commented
Hello @msfroh as you stated we can skip query generation for virtual sub-fields so made the changes accordingly 

1. In newObjectFieldExistsQuery skipped query generation by checking the virtual sub-fields
2. Modified expected case in the test case to skip virtual sub-fields like (_2gram, _3gram ...)
3. Re-Added throwing unsupportedexception for exists query (shall I remove it ?)

please review the changes and let me know if I need to make any additional changes

sorry for stalling MR was in the assumption that you have taken up the change for newObjectFieldExistsQuery

2024-03-27 22:44 UTC, msfroh approved these changes

2024-04-01 22:23 UTC, merged