Add Peer Recovery Stats in node/cluster stats
opensearch-project/OpenSearch pull request #12490
Opened 2024-02-28 09:26 UTC by Arpit-Bandejiya

### Description
[Describe what this change achieves]

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-12 03:32 UTC, ashking94 commented
@Arpit-Bandejiya  Lets add more details about what the change is about. Please also add sample response. Lets also mention that the stats are being stored in-memory and will be cleared during process restarts or node replacement.

2024-03-12 07:23 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
> +        if (out.getVersion().onOrAfter(Version.V_2_13_0)) {
This needs to be set to current initially and after the PR is merged, we need to set this to 2.13 version.

2024-03-12 07:25 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +import org.opensearch.indices.recovery.PeerRecoveryStats;
unused, please remove this.

2024-03-12 09:34 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +            builder.startObject("peer_recovery_stats");
lets have a static field for `peer_recovery_stats` as well.

2024-03-12 09:37 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +        private static final String TotalCancelledRecoveries = "total_cancelled_recoveries";
Is there an equation that these fields would always satisfy? For eg - total started would be sum of all remaining fields.
Can we please add details about such constraints and also add appropriate assertions for the same?

2024-03-12 09:40 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoverySourceService.java
> -
nit - lets remove this since no change.

2024-03-12 09:41 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java
> +    private final long total_cancelled_recoveries;
Lets add a bit more description about these fields please.

2024-03-12 09:42 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java
> +    private static final String TotalCancelledRecoveries = "total_cancelled_recoveries";
These seems to be duplicated in ClusterStatsNodes.java. Lets reuse the same fields here in the ClusterStatsNodes class.

2024-03-12 09:43 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +        private static final String TotalCancelledRecoveries = "total_cancelled_recoveries";
Improper java variable naming.

2024-03-12 09:44 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java
> +    private static final String TotalRetriedRecoveries = "total_retried_recoveries";
improper java variable naming. please follow the convention.

2024-03-12 09:47 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/replication/common/StatsAwareReplicationCollection.java
> +        tracker.incrementTotalRetriedRelocation(1);
What does reset mean in context of a peer recovery? How does this relate with a retry?

2024-03-12 09:48 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStatsTracker.java
> +    private final AtomicLong total_cancelled_recoveries;
Improper java variable naming, lets follow the convention.

2024-03-12 09:49 UTC, ashking94 commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStatsTracker.java
> +    }
Why do we need relocation in the names. Peer recovery does not necessarily mean a relocation.

2024-03-12 09:57 UTC, ashking94 commented on server/src/main/java/org/opensearch/node/Node.java
> +                peerRecoveryTargetService
Is this the only way to supply the peerRecoveryTargetService to the NodeService class?

2024-03-12 09:57 UTC, ashking94 requested changes
Lets also add UTs and ITs for this change.

2024-03-21 13:49 UTC, BhumikaSaini-Amazon requested changes
Thanks for the changes! We may need some updates (added in review). Please could you help add the UTs and ITs as well for the review?
 
Thanks

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on CHANGELOG.md
> +- Add Peer Recovery stats in node/cluster stats ([#12490](https://github.com/opensearch-project/OpenSearch/pull/12490))
Planned to be shipped in 3.0 or 2.x? If 2.x, please move this to the 2x section

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/action/admin/cluster/node/stats/NodeStats.java
> +        }
nit: It would be good to add a TODO here denoting the version update to be done

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on CHANGELOG.md
> +- Add Peer Recovery stats in node/cluster stats ([#12490](https://github.com/opensearch-project/OpenSearch/pull/12490))
Please also create a GH issue/PR on the docs repo for the respective documentation update and link it against the `Public documentation issue/PR created` checklist item in this PR's description

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java
> +    private final long total_cancelled_recoveries;
camelCase :)

```suggestion
    private final long totalStartedRecoveries;
    private final long totalFailedRecoveries;
    private final long totalCompletedRecoveries;
    private final long totalRetriedRecoveries;
    private final long totalCancelledRecoveries;
```

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +                    totalCancelledRecoveries += nodeStat.getPeerRecoveryStats().getTotalCancelledRecoveries();
We can call `nodeStat.getPeerRecoveryStats()` just once and store the result

```suggestion
                    PeerRecoveryStats peerRecoveryStats = nodeStat.getPeerRecoveryStats();
                    totalStartedRecoveries += peerRecoveryStats.getTotalStartedRecoveries();
                    totalFailedRecoveries += peerRecoveryStats.getTotalFailedRecoveries();
                    totalCompletedRecoveries += peerRecoveryStats.getTotalCompletedRecoveries();
                    totalRetriedRecoveries += peerRecoveryStats.getTotalRetriedRecoveries();
                    totalCancelledRecoveries += peerRecoveryStats.getTotalCancelledRecoveries();
```

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java
> +        long total_cancelled_recoveries
camelCase :)

```suggestion
        long totalStartedRecoveries,
        long totalFailedRecoveries,
        long totalCompletedRecoveries,
        long totalRetriedRecoveries,
        long totalCancelledRecoveries
```

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +    static class PeerRecoveryStats implements ToXContentFragment {
A lot of content here is duplicated from `server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStats.java` - can we avoid this?

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/action/admin/cluster/stats/ClusterStatsNodes.java
> +                    totalCancelledRecoveries += nodeStat.getPeerRecoveryStats().getTotalCancelledRecoveries();
Throughout the repo, we usually support this behaviour via an `add()` method in the respective `*Stats` class. Example: https://github.com/opensearch-project/OpenSearch/blob/53c0ce38b26569c90f8980f1c2b0b70e5ebbf6fc/server/src/main/java/org/opensearch/index/translog/RemoteTranslogStats.java#L156-L167

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/indices/recovery/PeerRecoveryStatsTracker.java
> +    }
If we want to support adding >1 value, the convention in the repo is to name the methods `add*()`. `increment*()` methods in the repo do not take an argument and enforce addition of 1.

2024-03-21 13:49 UTC, BhumikaSaini-Amazon commented on server/src/main/java/org/opensearch/indices/replication/common/StatsAwareReplicationCollection.java
> +    }
At this point, are the actual recovery operations (cancelling, starting, etc.) already done? If not, is it possible that we may update the respective stat but executing the actual operation might have failed? In such a case, peer recovery stats will show inconsistent data.

2026-05-01 12:34 UTC, closed without merging