Add user info in top queries
opensearch-project/OpenSearch pull request #12529
Opened 2024-03-04 21:18 UTC by ansjcy

### Description
Add user info and remote ip address for top n queries. 

### Related Issues
This is a follow up of https://github.com/opensearch-project/OpenSearch/pull/11904 to finish https://github.com/opensearch-project/OpenSearch/issues/11186

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-03-06 03:21 UTC, ansjcy commented
We shouldn't add dependencies on common-utils before we move queries insights to its own repo. Otherwise it will introduce circular dependency between OpenSearch core repo and common-utils repo.

2024-03-06 21:28 UTC, sandeshkr419 commented on plugins/query-insights/src/main/java/org/opensearch/plugin/insights/utils/ThreadContextParser.java
> +public final class ThreadContextParser {
Should we make this class as static?

2024-03-06 21:59 UTC, ansjcy commented
Discussed with .peternied, reading from thread context is actually not recommended. We should explore extending `IdentityPlugin` https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/IdentityPlugin.java#L19 for this purpose.

2024-03-06 22:37 UTC, peternied requested changes
@ansjcy Thanks for creating this PR - it sounds like a really useful feature for sysadmins.

This is a great use case for Identity - where information about who is operating a request should come from.  You can use the other plugin identity-shiro [1] to prove out your scenarios.

Furthermore there is a problem of 'userless' queries.  There are many system tasks and plugin operations via job scheduler that will not have user identity tied to them.  While not directly related if pulled from identity systems, the lack of insight here might warrant follow up work for your use case.  

If this PR is slimed down the the source - ip address that seems like a iterative step while building up support for exposing user identity.

- [1] https://github.com/opensearch-project/OpenSearch/tree/main/plugins/identity-shiro

2024-03-08 15:17 UTC, peternied reviewed
Is there an integration test for this scenario?  If not lets add one, or edit the existing test case to verify remote addresses are sensible.

2024-03-08 23:05 UTC, peternied reviewed
I am about to go on vacation so I won't be able to follow up for a while.

Fellow maintainers please feel free to dismiss my review when integration tests are added/updated to unblock merging of this PR. Thanks!

2024-03-08 23:05 UTC, peternied commented on plugins/query-insights/src/main/java/org/opensearch/plugin/insights/core/listener/QueryInsightsListener.java
> +            attributes.put(Attribute.REMOTE_ADDRESS, searchRequestContext.getRequestRemoteAddress());
Thanks for the detail. This might be an area to look into if it becomes cumbersome... such as the changes that were added for the unit test 😉

2024-03-15 00:15 UTC, msfroh commented on server/src/main/java/org/opensearch/rest/action/search/RestSearchAction.java
> +        searchRequest.remoteAddress(new TransportAddress(request.getHttpChannel().getRemoteAddress()));
I don't think it's safe to hijack `remoteAddress()` like this. 

It's intended to be set by `InboundHandler` on transport requests. Setting it on a REST request may have unintended consequences.

Also, if the request comes through a load balancer or a proxy, this value will almost certainly be the load balancer or proxy's address.

2024-03-18 21:57 UTC, ansjcy commented
Closing the PR as per peternied and froh's comments. We need to again carefully review what should be the best way to move forward to add user related information to top queries - Let's check the Identity service to see what are the gaps to get user info from there.

2024-03-18 21:57 UTC, closed without merging