Bump joda from 2.12.2 to 2.12.7
opensearch-project/OpenSearch pull request #13193
Opened 2024-04-15 14:44 UTC by cwperks

### Description

Bump joda from 2.12.2 to 2.12.7

### Related Issues
Resolves Whitesource issue: https://github.com/opensearch-project/security/pull/4153/checks?check_run_id=23766596951

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [X] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-15 15:07 UTC, reta approved these changes

2024-04-15 21:12 UTC, owaiskazi19 commented
@cwperks can you resolve the conflicts and push again? Thanks

2024-04-15 22:07 UTC, peternied commented
There is a regression introduced by this change 👎 @cwperks can you look into this?  
```
org.opensearch.common.time.DateUtilsTests.testTimezoneIds

java.lang.AssertionError: Antarctica/Vostok
Expected: <25200000>
     but: was <21600000>
```

2024-04-15 22:08 UTC, peternied requested changes
There is a regression introduced by the dependency change 👎

@cwperks can you look into this failure?  
```
org.opensearch.common.time.DateUtilsTests.testTimezoneIds

java.lang.AssertionError: Antarctica/Vostok
Expected: <25200000>
     but: was <21600000>
```

2024-04-15 23:57 UTC, cwperks commented
@peternied I fixed the error by updating the test. There's a list of IGNORE tzs in the test for this exact case. I was able to remove `America/Ciudad_Juarez` from this list and have it continue to work, but I had to add `Antarctica/Vostok` to the ignore list.

2024-04-16 00:57 UTC, reta approved these changes

2024-04-16 10:33 UTC, peternied approved these changes

2024-04-16 10:34 UTC, merged