Add the opensearch product header to threadContext
opensearch-project/OpenSearch pull request #13296
Opened 2024-04-19 04:06 UTC by llilyy

### Description
- As someone expand processing request or feature, etc., may want to know it is the context of the OpenSearch dashboard.
- Requests from the Opensearch dashboard have the `X-opensearch-product-origin` header. So I added this to the ThreadContext header list.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Failing checks are inspected and point to the corresponding known issue(s) (See: [Troubleshooting Failing Builds](../blob/main/CONTRIBUTING.md#troubleshooting-failing-builds))
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-04-19 18:35 UTC, dblock commented
What is the actual use-case where you need to know that the response is coming from OpenSearch? Typically server-side software is expressed with a `Server:` header, but for other custom headers I'd prefer it if we implemented https://github.com/opensearch-project/OpenSearch/issues/1069.

2024-04-20 21:27 UTC, kkmr commented on server/src/main/java/org/opensearch/rest/RestController.java
> +            if (request.header(OPENSEARCH_PRODUCT_ORIGIN_HTTP_HEADER) != null) {
Would it be possible to add a simple unit test for this?  Thanks!

2024-04-20 23:47 UTC, llilyy commented
@dblock 
Hi, I'm working on a custom OpenSearch plugin that print some logs about search requests of only OpenSearch Dashboard.
Knowing whether the request is for an OpenSearch dashboard may be a general use-case.
The OpenSearch dashboard is already adding the `X-opensearch-product-origin` header to requests. So I don't need to add custom headers to the request.
And I would like to add this header (`X-opensearch-product-origin`) to `ThreadContext` for internal use.

2024-04-22 13:10 UTC, dblock commented
@llilyy Thanks, I understand this now, you're just copying the header from the request to the thread context when it's present.

1. Add tests.
2. The code above checks `.... request.header(OPENSEARCH_PRODUCT_ORIGIN_HTTP_HEADER) == null`, reorder the checks to avoid having to lookup twice.
3. What is the side-effect and are there any negative implications of growing the thread context by this header? What if an application sends an extremely large header?

2024-04-22 21:25 UTC, jed326 commented
> What is the side-effect and are there any negative implications of growing the thread context by this header? What if an application sends an extremely large header?
Does it make sense to allow users to configure this/which headers get copied to thread context this way?
Should this be a boolean or a method on ThreadContext that says the request comes from OpenSearch?

+1 to this, I think allowing the user to copy headers into thread context this way introduces some risk. We could even  specifically check if the `OPENSEARCH_PRODUCT_ORIGIN_HTTP_HEADER` is `opensearch-dashboards` rather than accept all values.

2024-04-23 00:58 UTC, llilyy commented
@dblock @jed326 Thanks! I will check and edit codes.

2024-04-23 14:38 UTC, dblock requested changes
I think I like this a lot less, I'm sorry :( It makes OpenSearch be aware that the requester is OpenSearch Dashboards, which is a product dependency that doesn't need to exist. WDYT?

2024-04-24 00:59 UTC, llilyy commented
@dblock 
I agree. So how about adding a product header with the value `TURE` to `ThreadContext`?

```java
client.threadPool().getThreadContext().putHeader(OPENSEARCH_PRODUCT_ORIGIN_HTTP_HEADER, Boolean.TRUE.toString());
```

2024-04-24 03:14 UTC, cwperks commented
FYI The security plugin uses the ThreadContext to keep track of the remote address. It populates a TC header called ([`_opendistro_security_remote_address`](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/auth/BackendRegistry.java#L233-L239)) and takes into account proxied requests by resolving the XFF (X-Forwarded-For) header.

Its technically possible to read that header from another plugin, but that header is not explicitly populated for consumption by downstream plugins. The security plugin does populate [user info](https://github.com/opensearch-project/security/blob/main/src/main/java/org/opensearch/security/privileges/PrivilegesEvaluator.java#L214-L226) in the TC for plugins.

2024-04-24 13:08 UTC, cwperks commented
I also wanted to mention that the RestController has a feature called `headersToCopy` where it does copy request headers to the TC and you can find the headers list [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/ActionModule.java#L554-L557).

This gets passed to the constructor of the RestController [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/ActionModule.java#L576)

2024-04-25 00:45 UTC, dblock commented
The code looks fine. I am not sure what's best, to copy the header (in which case we should probably do what @cwperks suggests if it's already a pattern), or what is here. Maybe I can get some more opinions, @mch2 and @cwperks what would _you_ prefer?

2024-04-26 14:21 UTC, cwperks commented
@dblock I'd personally be in favor of using the existing mechanism, but curious to know what maintainers think.

2024-04-26 14:24 UTC, cwperks commented
@llilyy Does this comment work for your use-case? https://github.com/opensearch-project/OpenSearch/pull/13296#issuecomment-2079498549

2024-04-29 02:29 UTC, llilyy commented
@cwperks Thanks for your sharing. I will check it.

2024-04-29 07:58 UTC, llilyy commented
@cwperks 
I confirmed that it works well. thank you! I'll close the pr and issue.

2024-04-29 07:58 UTC, closed without merging