Add doc for debugging rest tests
opensearch-project/OpenSearch pull request #14491
Opened 2024-06-21 15:26 UTC by bowenlan-amzn

### Description
[Describe what this change achieves]

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- ~~[ ] Functionality includes testing.~~
- ~~[ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~~
- ~~[ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-06-21 16:39 UTC, mch2 approved these changes

2024-06-21 18:23 UTC, dblock requested changes
Let's make this a little clearer?

2024-06-21 18:23 UTC, dblock commented on TESTING.md
> +## Debug REST tests
Capitalize properly, "Debugging REST Tests"

2024-06-21 18:23 UTC, dblock commented on TESTING.md
> +Since Rest tests can be run against an external cluster. You can launch an OpenSearch cluster in debug mode following [Launching and debugging from an IDE](#launching-and-debugging-from-an-ide). And
The first sentence isn't complete, just combine it all: 

```
To run REST tests against an external cluster specify the following options.

...

You can also launch an OpenSearch cluster in debug mode following [Launching and debugging from an IDE](#launching-and-debugging-from-an-ide)
```.

2024-06-24 20:38 UTC, bowenlan-amzn commented
> Let's make this a little clearer and add to TOC please.

Thanks @dblock . I update the doc, pls take another look when you have time.

2024-06-25 19:34 UTC, dblock approved these changes

2024-06-25 19:35 UTC, merged