Fix missing value of FieldSort for unsigned_long
opensearch-project/OpenSearch pull request #14963
Opened 2024-07-24 17:11 UTC by bugmakerrrrrr

### Description
Two changes here:
1. Fixes parsing numeric missing value of unsigned long type. When we pass a numeric missing value like 4 to unsigned long field sort, the `ClassCastException` will be thrown(`class java.lang.Integer cannot be cast to class java.math.BigInteger `).
2. Requires the missing value of unsigned long type must not be negative.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-28 22:33 UTC, reta requested changes

2024-07-28 22:33 UTC, reta commented on server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
> +                long ul = ((Number) missingValue).longValue();
Please use `Numbers::toUnsignedLongExact`

2024-07-28 22:33 UTC, reta commented on server/src/main/java/org/opensearch/index/fielddata/fieldcomparator/UnsignedLongValuesComparatorSource.java
> +                    throw new IllegalArgumentException("missing value of type [unsigned_long] must not be negative");
For consistency with other error reports:

```suggestion
                    throw new IllegalArgumentException("Value [" + missingValue + "] is out of range for an unsigned long");
```

2024-07-29 13:30 UTC, reta commented
@bugmakerrrrrr could you please resolve the conflicts? thank you

2024-07-29 14:48 UTC, bugmakerrrrrr commented
> @bugmakerrrrrr could you please resolve the conflicts? thank you

Done

2024-07-29 16:57 UTC, reta approved these changes

2024-07-29 16:58 UTC, reta commented
@bugmakerrrrrr DCO check is failing sadly :(

2024-07-30 15:23 UTC, reta approved these changes

2024-07-30 15:24 UTC, merged