fix: MinHash token filter parameters not working
opensearch-project/OpenSearch pull request #15233
Opened 2024-08-13 19:09 UTC by mridehalgh

### Description
The [MinHash](https://opensearch.org/docs/latest/analyzers/token-filters/index/) token filter has four configurable parameters: bucket_count, hash_count, hash_set_size, and with_rotation. Currently both bucket_count and hash_set_size have no effect, because there appears to be a bug in the code that interfaces with the underlying Lucene class.

Notice the camel-case bucketCount and hashSetSize in the hasValue lines. These should be bucket_count and hash_set_size, since those are the parameter names that would appear (and be fetched on the following lines) from the settings object.

### Related Issues
Resolves #15183

### Check List
- [X] Functionality includes testing.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-13 21:24 UTC, dblock commented
Would you be able to check that this (and maybe other) token filter(s) are present in https://github.com/opensearch-project/opensearch-api-specification and add a test for this one?

2024-08-13 21:25 UTC, dblock approved these changes

2024-08-13 21:35 UTC, dblock requested changes
Needs a CHANGELOG update, thx.

2024-08-14 10:47 UTC, mridehalgh commented
> Needs a CHANGELOG update, thx.

@dblock - thanks for the quick feedback. Added changelog entry.

2024-08-15 18:57 UTC, dblock approved these changes

2024-08-15 18:57 UTC, dblock commented
> Thank you! Would you be able to check that this (and maybe other) token filter(s) are present in https://github.com/opensearch-project/opensearch-api-specification and add a test for this one in that repo?

@mridehalgh while this is getting rebased, care to take a look at ^ ?

2024-08-16 15:41 UTC, dblock commented
> ❌ Gradle check result for [26993dc](https://github.com/opensearch-project/OpenSearch/commit/26993dc0a33498dbd735002062b0ea890d3d5fb4): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/44668/)
> 
> Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?

I don't understand why this failed. @mridehalgh care to rebase to get the latest?

2024-08-16 17:06 UTC, mridehalgh commented
> > ❌ Gradle check result for [26993dc](https://github.com/opensearch-project/OpenSearch/commit/26993dc0a33498dbd735002062b0ea890d3d5fb4): [FAILURE](https://build.ci.opensearch.org/job/gradle-check/44668/)
> > Please examine the workflow log, locate, and copy-paste the failure(s) below, then iterate to green. Is the failure [a flaky test](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) unrelated to your change?
> 
> I don't understand why this failed. @mridehalgh care to rebase to get the latest?

@dblock neither do I. Rebasing :)

2024-08-16 19:02 UTC, dblock approved these changes

2024-08-16 19:11 UTC, merged

2024-08-16 19:13 UTC, dblock commented
@mridehalgh Looks like it will need a manual backport to 2.x please?