Fixing the deprecation warning for system indices to be logged once
opensearch-project/OpenSearch pull request #1537
Opened 2021-11-11 18:24 UTC by VachaShah

Signed-off-by: Vacha <vachshah@amazon.com>

### Description
The deprecation warnings for system indices to be logged once instead of spamming the user with multiple logs. 
 
### Issues Resolved
Closes #1108 
 
### Check List
- [ ] New functionality includes testing.
  - [X] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-11-11 23:21 UTC, dblock commented on server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
> +    private boolean isDeprecationWarningAlreadyLogged;
Does this need a default value?

2021-11-11 23:21 UTC, dblock commented on server/src/main/java/org/opensearch/cluster/metadata/IndexNameExpressionResolver.java
> +            if (resolvedSystemIndices.isEmpty() == false && !isDeprecationWarningAlreadyLogged) {
This has a potential race condition where two threads may end up logging and then flipping the value, no?

2021-11-11 23:22 UTC, dblock commented
Can we solve this generically in some way where the deprecation logger can be configured to log only once?

2021-11-12 00:21 UTC, VachaShah commented
> Can we solve this generically in some way where the deprecation logger can be configured to log only once from a given source? Might need to track those messages.

I tried the tracking messages in the IndexNameExpressionResolver since it prints the deprecation warning for different indices, but didn't go ahead with that I was concerned that the size of the collection where the messages are being tracked might grow a lot. As for handling it generically in deprecation logger, the deprecation logger is used at a lot of places in the code with different warnings to print. Some of the messages are quite similar ([example](https://github.com/opensearch-project/OpenSearch/blob/main/modules/analysis-common/src/main/java/org/opensearch/analysis/common/CommonAnalysisPlugin.java)). Maybe we can change the messages to make them more generic to making tracking easier and generic. WDYT?

2021-11-12 00:29 UTC, VachaShah commented
> ❌   Gradle Check failure [35cec89](https://github.com/opensearch-project/OpenSearch/commit/35cec8933b4eeaa60b155c685c92ac54b7deb1a4) [Log 1053](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1053.log)
> 
> [Reports 1053](https://ci.opensearch.org/logs/ci/workflow/OpenSearch_CI/PR_Checks/Gradle_Check/gradle_check_1053_reports.zip)

Gradle check failed with:
```
Expiring Daemon because JVM heap space is exhausted
Build timed out (after 120 minutes). Marking the build as failed.
Build was aborted
```

2021-11-12 00:57 UTC, VachaShah commented
start gradle check

2021-11-12 22:46 UTC, dblock requested changes
I think we want these deprecation messages to get wrapped into a class that is self-aware in terms of whether it has already been logged or not, then only log once. Otherwise we either have to track every message that gets logged, or end up with endless `if` and booleans all over the place where we log something.

2021-11-12 22:55 UTC, VachaShah commented
> I think we want these deprecation messages to get wrapped into a class that is self-aware in terms of whether it has already been logged or not, then only log once. Otherwise we either have to track every message that gets logged, or end up with endless `if` and booleans all over the place where we log something.

Definitely agree. I will work on this.

2021-12-06 19:40 UTC, closed without merging