[Backport 1.x] Bump icu4j from 62.1 to 75.1 (#15469)
opensearch-project/OpenSearch pull request #15482
Opened 2024-08-28 19:20 UTC by andrross

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>
(cherry picked from commit f5da8c8d8da644a92bcf5690182742d04b69e039)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-08-29 11:20 UTC, dblock approved these changes

2024-08-29 11:21 UTC, dblock requested changes
Looks like a legit failure?

2024-08-29 15:17 UTC, reta commented
62.2 is the latest we could update to :(

2024-08-29 15:46 UTC, reta approved these changes

2024-08-30 12:28 UTC, reta commented
@dblock apologies, mind please approving? thank you

2024-09-02 14:32 UTC, dblock approved these changes

2024-09-02 14:32 UTC, merged