Add wait in replica recovery for allocation id to propagate on source node
opensearch-project/OpenSearch pull request #15558
Opened 2024-09-01 15:21 UTC by gbbafna

### Description

When remote cluster state is enabled, cluster state propagation might get delayed . This cause replica recoveries to fail complaining that `source node does not have the shard listed in its state as allocated on the node` . This PR adds retry and backoff and gives some time for cluster state to get propagated and would prevent shards from failing due to same. 

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] Functionality includes testing.
- [ ] ~API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.~
- [ ] ~Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.~

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-03 15:05 UTC, ashking94 commented on server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
> +    public void testThrowExceptionOnNoTargetInRouting() throws IOException {
Comments on what we are doing would make this test more readable.

2024-09-03 15:05 UTC, ashking94 commented on server/src/test/java/org/opensearch/indices/recovery/LocalStorePeerRecoverySourceHandlerTests.java
> +        final RecoverySettings recoverySettings = new RecoverySettings(Settings.EMPTY, service);
Should we have a test around the case where after 2-3 retries the routing is found?

2024-09-03 15:06 UTC, ashking94 requested changes
Left some comments, pls address

2024-09-04 09:04 UTC, gbbafna commented on server/src/main/java/org/opensearch/indices/recovery/RecoverySourceHandler.java
> +
`run` doesn't return a value . I wanted to do it this way only, but found it infeasible.

2024-09-04 14:42 UTC, ashking94 approved these changes
can we add more comments within tests please?

2024-09-06 05:32 UTC, ashking94 approved these changes

2024-09-06 05:33 UTC, merged