Fix infinate loop in nested agg
opensearch-project/OpenSearch pull request #15931
Opened 2024-09-13 14:53 UTC by kkewwei

### Description
Fix infinate loop in nested agg

### Related Issues
Resolves #15914

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-09-14 08:43 UTC, dblock requested changes
Typo in CHANGELOG. Sorry!

2024-09-14 08:43 UTC, dblock commented on CHANGELOG.md
> +- Fix infinate loop in nested agg ([#15931](https://github.com/opensearch-project/OpenSearch/pull/15931))
```suggestion
- Fix infinite loop in nested agg ([#15931](https://github.com/opensearch-project/OpenSearch/pull/15931))
```

2024-09-14 08:44 UTC, dblock commented
If you are bored, you could add some tests for agg to https://github.com/opensearch-project/opensearch-api-specification and potentially fix any API spec problems with that ;)

2024-09-14 09:26 UTC, kkewwei commented
> If you are bored while gradle re-runs, you could add some tests for agg to https://github.com/opensearch-project/opensearch-api-specification and potentially fix any API spec problems with that ;)

Of course, let me have a try.

2024-09-14 10:34 UTC, kkewwei commented
> UNSTABLE

org.opensearch.remotestore.multipart.RemoteStoreMultipartIT #11997

2024-09-14 10:34 UTC, kkewwei commented
> ❕ Gradle check result for [ab0d430](https://github.com/opensearch-project/OpenSearch/commit/ab0d430adb300135b2c3faca75cc1cbea7596961): [UNSTABLE](https://build.ci.opensearch.org/job/gradle-check/47841/)
> 
> * **TEST FAILURES:**
> 
> ```
>       1 org.opensearch.remotestore.multipart.RemoteStoreMultipartIT.testNoSearchIdleForAnyReplicaCount
> ```
> 
> Please review all [flaky tests](https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#flaky-tests) that succeeded after retry and create an issue if one does not already exist to track the flaky failure.

org.opensearch.remotestore.multipart.RemoteStoreMultipartIT https://github.com/opensearch-project/OpenSearch/issues/11997

2024-09-15 10:21 UTC, dblock approved these changes

2024-09-17 17:57 UTC, sandeshkr419 commented on rest-api-spec/src/main/resources/rest-api-spec/test/search.aggregation/410_nested_aggs.yml
> +      reason: "fixed in 3.0.0"
I see backport label added to the PR. So most likely, this should get fixed in coming 2.18 release, right?
We should skip this for 2.17.99 ideally then?

2024-09-18 21:33 UTC, dbwiddis reviewed
LGTM. I will approve when the checklist at the top of this PR is completed.  Certainly there is testing (box 1) and an API spec (box 2) and it may not need a doc fix (box 3) but I'd prefer to see that assessment done by the PR submitter.

2024-09-19 08:48 UTC, merged

2024-09-19 18:59 UTC, reta commented
@kkewwei the issue seems to be not fixed, here is the recent failure (with this pull request merged): https://github.com/opensearch-project/OpenSearch/issues/15914#issuecomment-2361946004

2024-09-20 04:17 UTC, kkewwei commented
> @kkewwei the issue seems to be not fixed, here is the recent failure (with this pull request merged): [#15914 (comment)](https://github.com/opensearch-project/OpenSearch/issues/15914#issuecomment-2361946004)

Let me see.