[Tiered caching] Defining a new setting for tiered disk cache storage path
opensearch-project/OpenSearch pull request #16242
Opened 2024-10-08 21:24 UTC by sgup432

### Description
Adding new setting for disk cache storage path specifically  within tiered cache. Earlier we used specific cache implementation setting which might be confusing to user. This changes that now.

### Related Issues
Resolves #[Issue number to be closed when this PR is merged]

### Check List
- [x] Functionality includes testing.
- [x] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-10-08 22:24 UTC, sgup432 commented
@jainankitk

2024-10-09 00:51 UTC, sgup432 commented
Will pause on this. As we are keeping a empty default value inside storage setting, but still rely on a non empty default storagePath value coming from outside. Might be confusing. Will see if there is a way to do it.

2024-10-09 01:14 UTC, jainankitk requested changes
While the changes look fine as such, I have couple of concerns with including this storage path setting:

* Even though default setting is configured as blank, we are internally using some default value which is not very transparent for the users. Ideally they should be able to see that value using `_cluster/settings?include_defaults=true`
* Any disk storage path outside of data directory will not be accounted for within the DiskThreshold circuit breakers, that puts OpenSearch cluster at risk of going down

2025-01-30 00:38 UTC, jainankitk commented
@sgup432 - Can we close this PR if not relevant anymore?

2025-04-08 17:02 UTC, closed without merging