Make extended plugins optional
opensearch-project/OpenSearch pull request #16909
Opened 2024-12-24 00:19 UTC by cwperks

### Description

When a plugin extends another extensible plugin, OpenSearch requires the other plugin to be installed ahead of time.

This PR lifts the restriction and allows plugin installation. Instead, this PR warns the cluster administrator that the dependent plugin is missing and then prompts the user to continue with installation. If the dependent plugin is not installed, then the plugin being installed may only offer partial functionality.

In most use-cases, a plugin will extend another plugin because it offers core functionality. i.e. Anomaly detections needs job-scheduler to run detectors. In other cases, a plugin may extend another but only for a particular feature of the plugin that not all users will use. In such cases, does the extended plugin need to be installed if a user will never use the functionality?

While this doesn't make sense in all use-cases, the Security plugin would like to offer a SPI for plugins to share resources. In order for the security plugin to offer a SPI, other plugins would need to declare that they extend the security plugin. The problem with this is that security is optional and plugins currently support clusters where the security plugin is installed or clusters where it is not installed. By making extendedPlugins optional, this will allow security to offer a SPI but not be required for installation.

### Check List
- [ ] Functionality includes testing.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md), if applicable.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose), if applicable.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2025-01-02 22:22 UTC, cwperks commented
Re-opening this PR based on the conversation on https://github.com/opensearch-project/OpenSearch/pull/16030

2025-01-03 14:05 UTC, reta requested changes

2025-01-03 14:05 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +                logger.warn("Missing plugin [" + dependency + "], dependency of [" + name + "]");
I think you have suggested the notion of optional dependency for plugins? The default is "required" and has to be stay this way I believe, otherwise this is a breaking change.

2025-01-03 14:27 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +                logger.warn("Missing plugin [" + dependency + "], dependency of [" + name + "]");
It's not a breaking change, but I was also wondering what the best way to approach this was.

Its not breaking bc all dependencies still need to be installed to get the full features of the plugin being installed. If dependencies are missing then some functionality of the plugin being installed may not work.

There may be cases where a plugin is dependent on another plugin for a specific feature and the dependent plugin is required to be installed even if a cluster won't use the functionality provided by that feature. (I may be mistaken, but I think [SQA](https://opensearch.org/docs/latest/dashboards/management/scheduled-query-acceleration/#configuring-sqa-settings) could be an example of a feature that not all clusters may use, but its implementation requires job-scheduler to be installed).

In any case, it may be better to have an explicit `optionalExtendedPlugins` to support the use-case. I will look into what's required for the change.

2025-01-03 14:43 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +                logger.warn("Missing plugin [" + dependency + "], dependency of [" + name + "]");
> It's not a breaking change, but I was also wondering what the best way to approach this was.

This is tricky because we change the failure mode from installation to runtime.  We don't even know if plugin in question is even able to initialize without its dependency, so we may be spinning the services that would refuse to start. 

> In any case, it may be better to have an explicit optionalExtendedPlugins to support the use-case. I will look into what's required for the change.

We may follow the approach to have optional qualifier attached to plugin name, fe:

```
extendedPlugins = ['lang-painless;optional=true']
```

That would not be a breaking change, merely parsing of the string.

2025-01-03 15:28 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +                logger.warn("Missing plugin [" + dependency + "], dependency of [" + name + "]");
Pushed a commit to implement the `extendedPlugins = ['lang-painless;optional']` pattern.

2025-01-03 17:54 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +                logger.warn("Missing plugin [" + dependency + "], dependency of [" + name + "]");
Gradle check completed

2025-01-03 18:31 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +            String dependencyName = dependency.split(";")[0];
We cannot do that for bwc reasons:
 - please pre-parse in the `PluginInfo` (the `extendedPlugins` should be holding just plugin names as before)
 - please store optionality in separate list or it could be separate data structure, per your choice
 - please update `writeTo(final StreamOutput out)` / `PluginInfo(final StreamInput in)` to not send this additional optionality to the older nodes - they won't be able to interpret it properly

Just to reiterate the bwc part - we don't want "older" nodes to receive `dne;optional=true` (they would think this is a plugin name), we need to send `dne` only. Hope it makes sense.

2025-01-03 19:46 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +            String dependencyName = dependency.split(";")[0];
When is `PluginInfo` serialized and deserialized? I pushed a small change to exclude `;optional=true` when serializing PluginInfo and opted not to include any information about optionality when serializing/deserializing.

2025-01-03 19:53 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +            String dependencyName = dependency.split(";")[0];
Checking more of the calls to getExtendedPlugins()...

2025-01-03 20:21 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginsService.java
> +            String dependencyName = dependency.split(";")[0];
Yep, `ClusterStatsNodes`

2025-01-03 20:26 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        return extendedPlugins.stream().map(s -> s.split(";")[0]).collect(Collectors.toUnmodifiableList());
Why do we need that? `extendedPlugins` would never contain `;`, only plugin name

2025-01-03 20:27 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
```
if (in.getVersion().onOrAfter(Version.V_3_0_0)) {
    this.optionalExtendedPlugins = in.readStringList();
}
```

2025-01-03 20:28 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
Please also add it to `writeTo`, to keep serde consistent

2025-01-03 20:46 UTC, cwperks commented
Hit a new problem and not sure how to move forward...

Usually its the plugin being extended that will supply the SPI jar on the classpath and that would be the single instance of the jar in the node. 

When trying to make extended plugins optional, I can't rely on the extended plugin being installed and instead the extending plugin would need to provide the jar. If you have both the extended and the extending plugins providing the jar then it leads to jar hell.

2025-01-03 20:57 UTC, reta commented
> When trying to make extended plugins optional, I can't rely on the extended plugin being installed and instead the extending plugin would need to provide the jar.

The extending plugin has to have the `runtimeOnly` dependency on the plugin being extended, it should never bundle it. Since this becomes optional functionality now, it has to be propagated to the code level - if the classpath does not contain the extending plugin, the initialization of the related classes should not be triggered.

2025-01-03 21:04 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
Added, but why 3_0_0 and not 2_19_9?

2025-01-03 21:05 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        return extendedPlugins.stream().map(s -> s.split(";")[0]).collect(Collectors.toUnmodifiableList());
Removed this here. `extendedPlugins` will now have all regardless of optionality, but there would be another list that contains only the optional. Tested the Nodes Info API and confirmed its being returned:

```
...
"plugins" : [
  {
    "name" : "opensearch-index-management",
    "version" : "3.0.0.0-SNAPSHOT",
    "opensearch_version" : "3.0.0",
    "java_version" : "21",
    "description" : "OpenSearch Index Management Plugin",
    "classname" : "org.opensearch.indexmanagement.IndexManagementPlugin",
    "custom_foldername" : "",
    "extended_plugins" : [
      "opensearch-job-scheduler"
    ],
    "has_native_controller" : false,
    "optional_extended_plugins" : [
      "opensearch-job-scheduler"
    ]
  }
]
...
```

2025-01-03 21:24 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
> Added, but why 3_0_0 and not 2_19_0?

2.19 is fine, sometimes BWC tests may fail (since the change is not in 2.x branch)

2025-01-03 21:29 UTC, reta commented
Could you please create a documentation issue to document this change (and extended plugins in general) [1], we have done that for semantic versioning fe

[1] https://opensearch.org/docs/latest/install-and-configure/plugins/

2025-01-03 21:41 UTC, cwperks commented
> Could you please create a documentation issue to document this change (and extended plugins in general) [1], we have done that for semantic versioning fe
> 
> [1] https://opensearch.org/docs/latest/install-and-configure/plugins/

Opened a doc issue: https://github.com/opensearch-project/documentation-website/issues/9016

2025-01-03 21:47 UTC, cwperks commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
Changed to V_3_0_0 because of failing tests...after backport would there be a follow-up PR to update this value to 2_19_0?

2025-01-03 22:20 UTC, reta commented on server/src/main/java/org/opensearch/plugins/PluginInfo.java
> +        this.optionalExtendedPlugins = new HashSet<>();
Yep, thank you

2025-01-03 22:57 UTC, reta reviewed
@andrross any concerns / comments regarding this change? thank you!

2025-01-03 22:57 UTC, reta approved these changes

2025-01-03 23:11 UTC, andrross approved these changes

2025-01-03 23:11 UTC, merged

2025-01-03 23:24 UTC, cwperks commented
I'll open up a manual backport

2025-02-12 15:06 UTC, dblock commented
@cwperks This needs to be added to https://github.com/opensearch-project/opensearch-api-specification/, please?

See https://github.com/opensearch-project/opensearch-go/pull/669.

2025-02-12 16:12 UTC, cwperks commented
@dblock opened a PR on the opensearch-api-specification repo: https://github.com/opensearch-project/opensearch-api-specification/pull/814