Add request parameter 'cluster_manager_timeout' and deprecate 'master_timeout' - in Index APIs - part 1
opensearch-project/OpenSearch pull request #2660
Opened 2022-03-30 06:42 UTC by tlfeng

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-03-30 15:28 UTC, nknize requested changes
Same change request as in #2658

2022-03-30 20:21 UTC, tlfeng commented on server/src/main/java/org/opensearch/rest/action/admin/indices/RestCloseIndexAction.java
> +    private void parseDeprecatedMasterTimeoutParameter(CloseIndexRequest closeIndexRequest, RestRequest request) {
@nknize Thanks for reviewing this PR! I applied your suggested change in a new PR https://github.com/opensearch-project/OpenSearch/pull/2670. (I will continue this conversation in PR https://github.com/opensearch-project/OpenSearch/pull/2658#pullrequestreview-926303776)

2022-04-01 04:15 UTC, tlfeng commented on server/src/main/java/org/opensearch/rest/action/admin/indices/RestCloseIndexAction.java
> +    private void parseDeprecatedMasterTimeoutParameter(CloseIndexRequest closeIndexRequest, RestRequest request) {
The suggested change is merged with PR #2670, and I have updated this PR.

2022-04-01 05:32 UTC, tlfeng commented
In log 4016
```
> Task :client:rest-high-level:asyncIntegTest

REPRODUCE WITH: ./gradlew ':client:rest-high-level:asyncIntegTest' --tests "org.opensearch.client.documentation.IndicesClientDocumentationIT.testDeleteAlias" -Dtests.seed=DADB4A24C4FA8AC3 -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=it-CH -Dtests.timezone=Asia/Kuching -Druntime.java=17

org.opensearch.client.documentation.IndicesClientDocumentationIT > testDeleteAlias FAILED
    org.opensearch.client.WarningFailureException: method [DELETE], host [http://127.0.0.1:32983], URI [/index1/_alias/alias1?master_timeout=1m&timeout=2m], status line [HTTP/1.1 200 OK]
    Warnings: [Deprecated parameter [master_timeout] used. To promote inclusive language, please use [cluster_manager_timeout] instead. It will be unsupported in a future major version.]
    {"acknowledged":true}
        at __randomizedtesting.SeedInfo.seed([DADB4A24C4FA8AC3:3560A5B72A0A4E44]:0)
        at app//org.opensearch.client.RestClient.convertResponse(RestClient.java:346)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:320)
        at app//org.opensearch.client.RestClient.performRequest(RestClient.java:295)
        at app//org.opensearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1762)
        at app//org.opensearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1745)
        at app//org.opensearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1709)
        at app//org.opensearch.client.IndicesClient.deleteAlias(IndicesClient.java:1785)
        at app//org.opensearch.client.documentation.IndicesClientDocumentationIT.testDeleteAlias(IndicesClientDocumentationIT.java:2981)
```

2022-04-01 05:44 UTC, tlfeng commented
In log 4017
```
* What went wrong:
Execution failed for task ':qa:mixed-cluster:v2.1.0#mixedClusterTest'.
> `cluster{:qa:mixed-cluster:v2.1.0}` failed to wait for cluster health yellow after 40 SECONDS
    IO error while waiting cluster
    503 Service Unavailable
```

2022-04-02 00:48 UTC, tlfeng commented
In log 4054:
```
Execution failed for task ':client:rest-high-level:asyncIntegTest'.

Tests with failures:
 - org.opensearch.client.BulkProcessorIT.testGlobalParametersAndSingleRequest
 - org.opensearch.client.IndicesClientIT.testUpdateAliases
 - org.opensearch.client.IndicesClientIT.testClone
 - org.opensearch.client.IndicesClientIT.testShrink
 - org.opensearch.client.IndicesClientIT.testDeleteAlias
 - org.opensearch.client.IndicesClientIT.testGetFieldMapping
 - org.opensearch.client.IndicesClientIT.testSplit
 - org.opensearch.client.IndicesClientIT.testRollover
 - org.opensearch.client.IndicesClientIT.testGetMapping
 - org.opensearch.client.IndicesClientIT.testOpenExistingIndex
 - org.opensearch.client.IndicesClientIT.testDeleteIndex

291 tests completed, 11 failed, 1 skipped
```

2022-04-04 22:19 UTC, tlfeng commented
In log 4153:
```
REPRODUCE WITH: ./gradlew ':qa:mixed-cluster:v2.0.0#mixedClusterTest' --tests "org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT" -Dtests.method="test {p0=tasks.list/10_basic/tasks_list test}" -Dtests.seed=B4F39ACD8A2A3DED -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=es-PE -Dtests.timezone=Australia/ACT -Druntime.java=17

org.opensearch.backwards.MixedClusterClientYamlTestSuiteIT > test {p0=tasks.list/10_basic/tasks_list test} FAILED
    java.lang.AssertionError: Failure at [tasks.list/10_basic:15]: field [nodes.$node_id.roles] doesn't have a true value
    Expected: not null
         but: was null
        at __randomizedtesting.SeedInfo.seed([B4F39ACD8A2A3DED:3CA7A51724D65015]:0)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.executeSection(OpenSearchClientYamlSuiteTestCase.java:454)
        at org.opensearch.test.rest.yaml.OpenSearchClientYamlSuiteTestCase.test(OpenSearchClientYamlSuiteTestCase.java:427)
```
It's reproducible locally.

2022-04-05 04:14 UTC, nknize approved these changes
Oh yeah.. this is much cleaner!!! Nice work.

2022-04-05 04:17 UTC, tlfeng commented on rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_template.json
> +        "description":"Specify timeout for connection to master"
I forgot to deprecate the parameter here..

2022-04-05 04:24 UTC, tlfeng commented on rest-api-spec/src/main/resources/rest-api-spec/api/indices.get_template.json
> +        "description":"Specify timeout for connection to master"
Updated in commit https://github.com/opensearch-project/OpenSearch/pull/2660/commits/b914741f9683edc583b7ca6ebc0b5615db08d248

2022-04-05 05:15 UTC, nknize commented
#1703 strikes again!

2022-04-05 05:15 UTC, nknize commented
start gradle check

2022-04-05 06:18 UTC, tlfeng commented
In log 4188:
```
* What went wrong:
Execution failed for task ':modules:analysis-common:test'.
> Process 'Gradle Test Executor 446' finished with non-zero exit value 1
  This problem might be caused by incorrect test process configuration.
  Please refer to the test execution section in the User Manual at https://docs.gradle.org/7.4.2/userguide/java_testing.html#sec:test_execution
```
start gradle check

2022-04-05 17:47 UTC, merged