Add `positive_score_impact` support for `rank_features`
opensearch-project/OpenSearch pull request #2726
Opened 2022-04-03 21:44 UTC by Hronom

### Description
Added support for `positive_score_impact` parameter for `rank_features`
 
### Issues Resolved
[[List any issues this PR will resolve]](https://github.com/opensearch-project/OpenSearch/issues/2724)
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-04 00:12 UTC, Hronom commented
start gradle check

2022-04-04 00:13 UTC, Hronom commented
Admins please restart build... since failed test completed ok locally and changes also works good here https://github.com/opensearch-project/OpenSearch/pull/2725

2022-04-04 04:11 UTC, nknize requested changes
We will not be releasing 1.4 and 2.0 is feature frozen so the earliest we can merge this will be for 2.1. Let's work on getting it in main first and then we'll autobackport to 2.x.

2022-04-04 13:42 UTC, reta commented on modules/mapper-extras/src/main/java/org/opensearch/index/mapper/RankFeaturesFieldMapper.java
> +        private final boolean positiveScoreImpact;
It seems like `positiveScoreImpact` is not needed for `RankFeaturesFieldType`, the `positiveScoreImpact()` is never used

2022-04-04 15:28 UTC, nknize commented
Please fold the above PR feedback into #2725. We will not be merging this into 1.x since there will be no 1.4 release.

2022-04-11 17:19 UTC, dblock commented
I'll close this and leave https://github.com/opensearch-project/OpenSearch/pull/2725. Once in main we can talk about how far we want to backport it.

2022-04-11 17:19 UTC, closed without merging