Add 2.0.0-rc1 release notes
opensearch-project/OpenSearch pull request #3044
Opened 2022-04-22 16:43 UTC by Poojita-Raj

Signed-off-by: Poojita Raj <poojiraj@amazon.com>

### Description
Adding release notes for the 2.0 release. There was no common branch point to start the release notes from - so it started from commit f14e0a36c48ecb8d2f58b37cc18e86d3b6836319 - the commit after #2489. Dependabot PRs have been removed for the sake of brevity.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-22 19:35 UTC, nknize requested changes
Rebase from main to ensure passing tests.

2022-04-22 21:35 UTC, dblock requested changes
These notes need to be humanly readable. This isn't really. So I am afraid we need to hand-edit this entire file.

![Screen Shot 2022-04-22 at 5 34 21 PM](https://user-images.githubusercontent.com/542335/164798951-49b91fac-7d83-404e-b3a8-97927c756034.png)

@elfisher @bbarani can agree/disagree

2022-04-22 21:48 UTC, dblock commented
Check out what https://github.com/opensearch-project/job-scheduler/pull/172 looks like, I think I expected something like that here.

2022-04-25 18:28 UTC, dblock requested changes
I would just keep the titles and make the GitHub issues clickable. Like in https://github.com/opensearch-project/job-scheduler/pull/172/files.

2022-04-25 18:28 UTC, dblock commented on release-notes/opensearch.release-notes-2.0.0-rc1.md
> +* __Add type mapping removal bwc tests for indexing, searching, snapshots (#2901)__
I'd want those issues to be clickable.

2022-04-26 20:33 UTC, dblock reviewed
Much better! Do you think it's worth doing a pass on aligning language/standardizing things like `[Remove] Xyz ...`, capitalizing consistently, etc.?

2022-04-26 20:43 UTC, Poojita-Raj commented
> Much better! Do you think it's worth doing a pass on aligning language/standardizing things like `[Remove] Xyz ...`, capitalizing consistently, etc.?

I don't think it's worth it since a lot of the titles would require a manual rewrite to ensure they're in the same format - not all of them start with action verbs or tags. But going forward definitely we should ensure all PRs have a check to ensure they're in the right format - referencing the discussion in #1868.

2022-04-26 21:50 UTC, kartg approved these changes
Kudos for combing through all of the commits and crafting this!

2022-04-27 01:13 UTC, merged