Support Java 8 for opensearch-rest-client
opensearch-project/OpenSearch pull request #3181
Opened 2022-05-04 14:58 UTC by dlvenable

### Description

This PR sets the source and target compatibility to Java 8 for the `opensearch-rest-client`. Additionally, it sets the client-test project to use Java 8 since `opensearch-rest-client` depends on it.

This should ensure that only Java 8 language features compile for these projects. However, it cannot verify that only Java 8 APIs are in use. I believe OpenSearch would need to use Gradle toolkits and run on a machine with both Java 11 and Java 8 for this.
 
### Issues Resolved

This addresses:
https://github.com/opensearch-project/opensearch-clients/issues/20
 
### Verification

1) Download the 2.0.0-rc1 `opensearch-rest-client`:

```
wget https://repo1.maven.org/maven2/org/opensearch/client/opensearch-rest-client/2.0.0-rc1/opensearch-rest-client-2.0.0-rc1.module
```

2) Examine the Gradle module file. It requires Java 11.

```
grep jvm opensearch-rest-client-2.0.0-rc1.module
        "org.gradle.jvm.version": 11,
        "org.gradle.jvm.version": 11,
```

3) Build OpenSearch locally with the change.

```
./gradlew clean assemble
./gradlew publishToMavenLocal
```

4) Verify Java 8 in the Gradle module file

```
grep jvm ~/.m2/repository/org/opensearch/client/opensearch-rest-client/3.0.0-SNAPSHOT/opensearch-rest-client-3.0.0-SNAPSHOT.module
        "org.gradle.jvm.version": 8,
        "org.gradle.jvm.version": 8,
```

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-04 16:23 UTC, reta commented
@dlvenable I don't think we should go forward with this change:
 - moving baseline to JDK-11 is intentional (and aligned with projects Opensearch depends on) 
 - we recommend to use `highlevel-rest-client` and it requires JDK-11
 - downgrading `rest-client` to 1.8 won't help `opensearch-java` since it depends on test framework [1] and will require JDK-11

[1] https://github.com/opensearch-project/opensearch-java/blob/main/java-client/build.gradle.kts#L132

2022-05-04 19:11 UTC, dblock commented
I agree with @reta. 

But if we decided to do this, for starters, we would need to also re-add Java 8 CI but only run tests for this part of the project on JDK8. What's the pull for that?

2022-05-05 20:46 UTC, dblock requested changes
Let's leave this open for now until we have a path forward for clients that run on JDK8. Thanks for your help @dlvenable.

2022-05-10 18:53 UTC, dblock reviewed
I am not against this. 

Try adding a JDK8 CI part of this? Without it we have no hope of ever preserving future compatibility.

2022-05-10 18:53 UTC, dblock commented on client/rest/build.gradle
> +  //client does not depend on shamcreerver, so only jdk and http signatures should be checked
bulk replace at work? :)

2023-02-09 19:27 UTC, wbeckler commented
Any thoughts on the next steps on this? If someone's client has to be Java 8, what's the recommendation for them? Here's an example of someone who is stuck due to the java 11 requirement for opensearch-java: https://forum.opensearch.org/t/opensearch-1-3-x-gradle-build-problem-w-java-8/12400

2023-02-10 00:50 UTC, reta commented
> Any thoughts on the next steps on this? If someone's client has to be Java 8, what's the recommendation for them? Here's an example of someone who is stuck due to the java 11 requirement for opensearch-java: https://forum.opensearch.org/t/opensearch-1-3-x-gradle-build-problem-w-java-8/12400

@wbeckler  I think, what we could here is:
 - `rest-client` goes back to JDK-8 baseline (@dblock we don't need to have JDK-8 CI for it, setting source / target level to 1.8 or release should be enough)
 - `opensearch-java` goes back to JDK-8 baseline, but we would need to build it with JDK-11 (or above) since it uses test framework from core

@dblock @dlvenable what do you think folks?

2023-02-10 03:09 UTC, dlvenable commented
> rest-client goes back to JDK-8 baseline (@dblock we don't need to have JDK-8 CI for it, setting source / target level to 1.8 or release should be enough)

Is there a need to move this back to JDK 8? It seems work in opensearch-java can provide users with an option of using JDK 8. Of course, this does mean that users would need to use opensearch-java instead of rest-client.

> opensearch-java goes back to JDK-8 baseline, but we would need to build it with JDK-11 (or above) since it uses test framework from core

If users are still blocked on JDK 8, then I think we should do this. The recent changes will allow opensearch-java to decouple from OpenSearch core and have its own JDK versions based on user needs.

2023-02-10 17:21 UTC, andrross commented
>> The recent changes will allow opensearch-java to decouple from OpenSearch core and have its own JDK versions based on user needs.
>
> Yes and no, we still have to support rest-client based transport, and if we want to do that in a way to not require users to use JDK-11 or above, we have to be on JDK-8 all way through.

@reta Is there anyway to accelerate this decoupling? I know it's gross but could we copy the `rest-client` implementation into opensearch-java? Support for a JDK-8 client seems like a reasonable request but I would hate to burden the entire server implementation with JDK-8 support due to this coupling.

2023-02-10 17:40 UTC, reta commented
> @reta Is there anyway to accelerate this decoupling? I know it's gross but could we copy the `rest-client` implementation into opensearch-java? 

Hm ... let see, if we copy, we have to preserve the same packaging (so people won't see the different) - this part is fine. But if there is an old `rest-client` dependency on the classpath (transitive or not) - we are in trouble, more than one class under the same package on classpath, that would not be fun. 
> Support for a JDK-8 client seems like a reasonable request but I would hate to burden the entire server implementation with JDK-8 support due to this coupling.

Oh, `rest-client` would be one off exception - to stay on JDK-8 bytecode, everything else moves forward.

2023-02-10 18:34 UTC, reta commented
> Because it would definitely fail at runtime with JDK-8.

Yes, we need to make sure that `opensearch-java` does not use features which are not supported by JDK-8, but that we could do with source/target or release setting (so the build will fail).

2023-02-10 19:27 UTC, dlvenable commented
> Hm ... let see, if we copy, we have to preserve the same packaging (so people won't see the difference) - this part is fine. But if there is an old rest-client dependency on the classpath (transitive or not) - we are in trouble, more than one class under the same package on classpath, that would not be fun.

This can be considered a breaking change. I believe the last release of opensearch-java was 2.2.0 so there is still a 3.0.0 available. We can give clear guidance on how to remove the transitive dependency on the old rest-client as part of the instructions. 

Alternatively, we could use a different Java package name from the original. This would require that customers update all of their package names in their code. But, it would probably be safer.

This is a hard change to be making, but I believe that this decoupling will be great for users!

2023-02-10 19:48 UTC, andrross commented
> This can be considered a breaking change.

Is it feasible to remove the OpenSearch core dependency and `RestClientTransport` all together in 3.0 and instruct users to use `ApacheHttpClient5Transport` instead? Then 3.0 could be built with JDK-8 support and that would offer a path forward for any JDK-8 users.

2023-02-10 20:05 UTC, reta commented
> > This can be considered a breaking change.
> 
> Is it feasible to remove the OpenSearch core dependency and `RestClientTransport` all together in 3.0 and instruct users to use `ApacheHttpClient5Transport` instead? Then 3.0 could be built with JDK-8 support and that would offer a path forward for any JDK-8 users.

@andrross the plan for deprecation + gradual removal is here https://github.com/opensearch-project/opensearch-java/issues/326

2023-02-14 15:00 UTC, dblock commented
I haven't heard anything from any new users about needing JDK8, has anyone? Decoupling brings a lot of other benefits. I propose we close this PR without merging and focus on opensearch-java decoupling (and restoring JDK8 support there with new code).

2023-02-20 17:39 UTC, wbeckler commented
To answer @dblock's question, we recently heard a need on the forum for Java 8: https://forum.opensearch.org/t/opensearch-1-3-x-gradle-build-problem-w-java-8/12400/5

The big need for this comes from the opensearch-hadoop situation. Today elasticsearch-hadoop is Java 8 compatible. If we want to integrate opensearch-java into opensearch-hadoop to reduce the overall java surface area, today it would be a breaking change in an environment with lots of legacy Java 8 stuff in the Hadoop and Spark applications that would consume the opensearch-hadoop client.

2023-02-20 18:12 UTC, reta commented
> To answer @dblock's question, we recently heard a need on the forum for Java 8: https://forum.opensearch.org/t/opensearch-1-3-x-gradle-build-problem-w-java-8/12400/5

Somewhat related story is on Apache Flink side https://github.com/apache/flink-connector-opensearch/pull/4

2023-07-24 15:21 UTC, closed without merging