Remove old license header from new files created during master terminology replacement
opensearch-project/OpenSearch pull request #3924
Opened 2022-07-15 18:01 UTC by tlfeng

### Description
- Remove the old license header from newly created class files. The files are created during master terminology replacement to maintain the backwards compatibility of the public classes.

Class file list:
MasterNodeOperationRequestBuilder
MasterNodeReadOperationRequestBuilder
MasterNodeReadRequest
MasterNodeRequest
TransportMasterNodeAction
TransportMasterNodeReadAction
NoMasterBlockService
UnsafeBootstrapMasterCommand
LocalNodeMasterListener
MasterNodeChangePredicate
NotMasterException
MasterNotDiscoveredException
RestMasterAction

### Issues Resolved
Comes from https://github.com/opensearch-project/OpenSearch/pull/3914#discussion_r921714472

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-15 18:02 UTC, dreamer-89 approved these changes

2022-07-15 18:04 UTC, tlfeng commented
@dreamer-89  Thanks a lot for your rapid review! 👍👍

2022-07-15 18:46 UTC, tlfeng commented
In build 696:
```
> Task :server:internalClusterTest

REPRODUCE WITH: ./gradlew ':server:internalClusterTest' --tests "org.opensearch.index.ShardIndexingPressureSettingsIT.testShardIndexingPressureEnforcedEnabledDisabledSetting" -Dtests.seed=17073FD017DD65FD -Dtests.security.manager=true -Dtests.jvm.argline="-XX:TieredStopAtLevel=1 -XX:ReservedCodeCacheSize=64m" -Dtests.locale=sq-AL -Dtests.timezone=Asia/Karachi -Druntime.java=17

org.opensearch.index.ShardIndexingPressureSettingsIT > testShardIndexingPressureEnforcedEnabledDisabledSetting FAILED
    java.lang.Exception: Test abandoned because suite timeout was reached.
        at __randomizedtesting.SeedInfo.seed([17073FD017DD65FD]:0)
```

2022-07-15 19:15 UTC, dreamer-89 commented
Java heap space causing build failure. Even though the build marked successful. 

```
> Task :qa:mixed-cluster:v2.2.0#bwcTest
> Task :qa:mixed-cluster:bwcTestSnapshots
> Task :qa:mixed-cluster:check
build complete, generating: /var/jenkins/workspace/gradle-check/search/build/697.tar.bz2

BUILD SUCCESSFUL in 24m 9s
2594 actionable tasks: 2580 executed, 2 from cache, 12 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Java heap space

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24m 9s
Gradle Check Failed!
```

2022-07-15 21:22 UTC, owaiskazi19 requested changes
Let's not change the license header for old files of ES

2022-07-16 03:37 UTC, tlfeng commented
Close this PR, because there is concern to remove the old license headers. Although the files are newly created, the file name is the same as those present in ES.

2022-07-16 03:37 UTC, closed without merging