It is possible to disable NodeAndClusterIdConverter plugin.
opensearch-project/OpenSearch pull request #4322
Opened 2022-08-29 16:53 UTC by lukasz-soszynski-eliatra

### Description
New system property `org.opensearch.common.logging.NodeAndClusterIdConverter.enabled` added to disable custom Log4j2 plugin NodeAndClusterIdConverter. 

Probably this change needs to be merged to another or additional branch.

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-08-29 20:45 UTC, dblock requested changes
Would you mind explaining why you need this?

Is there precedent where we disable other logging plugins this way elsewhere in the code?

Either way will need tests.

2022-08-30 08:13 UTC, lukasz-soszynski-eliatra commented
This PR is related to the integration tests for the OpenSearch security plugin. For more details, please see the conversation in another PR: https://github.com/opensearch-project/security/pull/1967#discussion_r957575866

2022-09-05 10:25 UTC, lukasz-soszynski-eliatra commented
I have pushed unit tests related to the modified code fragments.

2022-09-07 08:40 UTC, lukasz-soszynski-eliatra commented
I noticed that the build fails with the following error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 2.2.1 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/bugfix/build/bwc/checkout-2.2/distribution/archives/linux-tar/build/distributions/opensearch-min-2.2.1-SNAPSHOT-linux-x64.tar.gz
```

I found another error message which seems to be related to the problem:
```
> Task :distribution:bwc:bugfix:buildBwcLinuxTar FAILED
 [2.2.1] > Task :distribution:archives:buildLinuxTar
 [2.2.1] > Task :distribution:archives:linux-tar:assemble
 [2.2.1] build complete, generating: /var/jenkins/workspace/gradle-check/search/distribution/bwc/bugfix/build/bwc/checkout-2.2/build/[2708.tar.bz](http://2708.tar.bz/)2
 [2.2.1] 
 [2.2.1] BUILD SUCCESSFUL in 3m 38s
 [2.2.1] 169 actionable tasks: 169 executed
```

Unfortunately, both error messages are not very descriptive. @peternied could you help to figure out what is wrong, please?

2022-09-08 15:59 UTC, peternied commented
> The following warning ApplierService#updateTask][T#1] WARN ClusterApplierService:628 - failed to notify ClusterStateListener occurs when two or more OpenSearch nodes are run in a single JVM. The root cause of the problem is related to the custom Log4j2 plugin NodeAndClusterIdConverter. The plugin stores node and cluster id in the static field

@lukasz-soszynski-eliatra I'm not sure this is the right change, from your description I think the issue is that we cannot run more than one OpenSearch node inside a single JVM without this issue coming up.  It seems like the static field should be modified so it can handle this scenario - that would address the root cause.

If you don't see a way to address the root cause, then I'd recommend creating can create an issue on OpenSearch so it can be triaged / reviewed, then we could work around it by overloading the logger with like was done here for [JarHell](https://github.com/DarshitChanpura/security/blob/6d6fd75c6980db6e138c345cc62661e429bd8f07/src/test/java/org/opensearch/bootstrap/JarHell.java) - see where it was discussed https://github.com/opensearch-project/OpenSearch/issues/3905

2022-09-09 10:06 UTC, lukasz-soszynski-eliatra commented
@peternied  I created an issue: https://github.com/opensearch-project/OpenSearch/issues/4466

2022-12-13 23:29 UTC, peternied commented
@lukasz-soszynski-eliatra I'm going to close this PR out as I don't think this will be moved forward with.  Thanks for the issue!

2022-12-13 23:29 UTC, closed without merging