Compiler warning
opensearch-project/OpenSearch pull request #4796
Opened 2022-10-14 18:08 UTC by mloufra

Signed-off-by: mloufra <mloufra@amazon.com>

### Description
Add unbounded wildcard for RegisterTransportActionsRequest constructor to clean up compiler warning
Equivalent PR on OpenSearch-sdk-java:  

### Issues Resolved
https://github.com/opensearch-project/opensearch-sdk-java/issues/130

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-14 18:34 UTC, dbwiddis commented
@mloufra Can you edit your title to add `[Feature/extensions]` as a prefix so the maintainers know our team is handling it?

2022-10-14 19:21 UTC, dbwiddis requested changes
We generally put the feature/extensions tag at the beginning of the title.   A more descriptive title than "Compiler Warning" might be helpful, such as "Enforce type safety for RegisterTransportActionsRequest".

Also per CI checks you need a change log.

2022-10-14 19:21 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/RegisterTransportActionsRequest.java
> +    public RegisterTransportActionsRequest(String uniqueId, Map<String, Class<?>> transportActions) {
This is called from the SDK with this line:
```java
new RegisterTransportActionsRequest(uniqueId, transportActions),
```
See [comment here](https://github.com/opensearch-project/opensearch-sdk-java/pull/195#discussion_r996065662) for narrower types needed.

2022-10-17 22:31 UTC, owaiskazi19 commented
@mloufra you need to make the changes in test files as well
```
/home/runner/work/OpenSearch/OpenSearch/server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java:24: error: incompatible types: inference variable V has incompatible bounds
        this.originalRequest = new RegisterTransportActionsRequest("extension-uniqueId", Map.of("testAction", Map.class));
> Task :server:compileTestJava
                               ^
    equality constraints: Class<? extends TransportAction<? extends ActionRequest,? extends ActionResponse>>
    lower bounds: Class<org.opensearch.common.collect.Map>
  where V,K are type-variables:
    V extends Object declared in method <K,V>of(K,V)
    K extends Object declared in method <K,V>of(K,V)
/home/runner/work/OpenSearch/OpenSearch/server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java:132: error: incompatible types: inference variable V has incompatible bounds
        RegisterTransportActionsRequest request = new RegisterTransportActionsRequest(

2022-10-17 22:35 UTC, mloufra commented
> @mloufra you need to make the changes in test files as well
> 
> ```
> /home/runner/work/OpenSearch/OpenSearch/server/src/test/java/org/opensearch/extensions/RegisterTransportActionsRequestTests.java:24: error: incompatible types: inference variable V has incompatible bounds
>         this.originalRequest = new RegisterTransportActionsRequest("extension-uniqueId", Map.of("testAction", Map.class));
> > Task :server:compileTestJava
>                                ^
>     equality constraints: Class<? extends TransportAction<? extends ActionRequest,? extends ActionResponse>>
>     lower bounds: Class<org.opensearch.common.collect.Map>
>   where V,K are type-variables:
>     V extends Object declared in method <K,V>of(K,V)
>     K extends Object declared in method <K,V>of(K,V)
> /home/runner/work/OpenSearch/OpenSearch/server/src/test/java/org/opensearch/extensions/action/ExtensionTransportActionsHandlerTests.java:132: error: incompatible types: inference variable V has incompatible bounds
>         RegisterTransportActionsRequest request = new RegisterTransportActionsRequest(
> ```

Thanks for the reminder, I'm trying to fix this.

2022-10-18 16:53 UTC, dbwiddis approved these changes

2022-10-18 16:54 UTC, dbwiddis approved these changes
Changes here look good, per other comment need to also update test files.

2022-10-18 19:48 UTC, saratvemulapalli approved these changes

2022-10-21 18:33 UTC, dbwiddis approved these changes

2022-10-21 19:16 UTC, owaiskazi19 approved these changes

2022-10-21 19:16 UTC, merged