Add detailed message when return "Invalid argument" of IllegalArgumentException
opensearch-project/OpenSearch pull request #5350
Opened 2022-11-23 07:45 UTC by xuezhou25

### Description
This PR is an alternative approach of https://github.com/opensearch-project/OpenSearch/pull/4792 As the previous PR may have some potential compatibility issues. New PR can do the change in a more backward compatible way.

With the setting `http.detailed_errors.enabled: false`:
```
curl -XPUT "http://localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
"persistent" : {
        "http.detailed_errors.enabled": true
    }
}'
{"error":"Invalid argument","status":400}
```
After change:
```
curl -XPUT "http://localhost:9200/_cluster/settings" -H 'Content-Type: application/json' -d'
{
"persistent" : {
        "http.detailed_errors.enabled": true
    }
}'
{"error":"Invalid argument[persistent setting [http.detailed_errors.enabled], not dynamically updateable]","status":400}
```

### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/4745

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-23 08:39 UTC, owaiskazi19 commented on server/src/main/java/org/opensearch/ExceptionsHelper.java
> +                return "Invalid argument" + "[" + t.getMessage() + "]";
```suggestion
                return "Invalid argument [" + t.getMessage() + "]";
```

2022-11-23 16:28 UTC, owaiskazi19 approved these changes

2022-11-23 16:34 UTC, andrross commented
@reta Any thoughts here? The main issue is whether there are any information leakage concerns with this change.

2022-11-28 17:37 UTC, dblock requested changes
@xuezhou25 looks like there are some security concerns, care to address?

2023-01-11 06:56 UTC, xuezhou25 commented
Will choose the previous way in this pr#4792

2023-01-11 06:56 UTC, closed without merging