Upgrade the mappings on .tasks index if needed (#5376)
opensearch-project/OpenSearch pull request #5377
Opened 2022-11-24 16:41 UTC by pbruski

Signed-off-by: Przemek Bruski <pbruskispam@op.pl>

### Description
Upgrade the mappings on .tasks index if needed. This fixes an regression introduced in https://github.com/opensearch-project/OpenSearch/pull/1732

### Issues Resolved
[[List any issues this PR will resolve]](https://github.com/opensearch-project/OpenSearch/issues/5376)

### Check List
- [X] New functionality includes testing.
- [X] All tests pass
- [X] New functionality has been documented.
- [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-11-25 00:46 UTC, martin-gaievski commented
Is it possible to add test around this scenario so we more confident that it will not break in future releases?

2022-11-26 01:25 UTC, pbruski commented
> Is it possible to add test around this scenario so we more confident that it will not break in future releases?

How I'd do it?
1. I think the mapping update could be done regardless of the version.
2. Guarding against a change in mapping without corresponding changes in versions could be done via a commit hook.
3. Ultimately, the only real solution to this problem is a test suite that does an upgrade of OpenSearch in a baseline version to the current/master version and runs integration tests on it.

2022-11-28 17:48 UTC, dblock requested changes
Since this is a regression, let's add a test for this?

2022-11-28 17:48 UTC, dblock commented on CHANGELOG.md
> +- after upgrade to OpenSearch 2.0, finished tasks no longer get stored in .tasks index ([#5376](https://github.com/opensearch-project/OpenSearch/issues/5376))
Let's make this look like the other lines, please? 

"Fixed storing finished tasks in .tasks index"

2022-11-28 18:06 UTC, dblock commented
> > Is it possible to add test around this scenario so we more confident that it will not break in future releases?
> 
> How I'd do it?
> 
> 1. I think the mapping update could be done regardless of the version.
> 2. Guarding against a change in mapping without corresponding changes in versions could be done via a commit hook.
> 3. Ultimately, the only real solution to this problem is a test suite that does an upgrade of OpenSearch in a baseline version to the current/master version and runs integration tests on it.

We have bcw tests exactly for this scenario! I've never written one myself, but if you can't figure it out we'll find someone to help. Start here: https://opensearch.org/blog/technical-post/2021/11/bwc-testing-for-opensearch/

2022-11-30 18:58 UTC, andrross commented
@pbruski Thanks for the contribution here! I've gone ahead and created #5412 which takes your fix here as well as modifies the existing compatibility test to catch these types of problems in the future.

2022-11-30 23:13 UTC, andrross commented
Closing as this has been resolved in #5412

Thanks again @pbruski !

2022-11-30 23:13 UTC, closed without merging

2022-12-02 13:49 UTC, pbruski commented
@andrross Thanks for taking this over - honestly, I have no idea when I'd find the time to dig into the test infra and write that test...