[Feature/extensions] Renaming tests to be consistent with main branch
opensearch-project/OpenSearch pull request #5571
Opened 2022-12-14 20:57 UTC by ryanbogan

Signed-off-by: Ryan Bogan <rbogan@amazon.com>

### Description
Renaming tests to be consistent with main branch

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-14 22:18 UTC, ryanbogan commented
The test that is failing is also broken on main - I will rebase once the fix is pushed there.

2022-12-14 22:42 UTC, dreamer-89 commented
Last few gradle check failures happening due to version bump after 2.4.1 release, https://github.com/opensearch-project/OpenSearch/pull/5560. Fixed is merged into main branch. @ryanbogan : Can you please rebase your branch against latest `main` branch ?
```
* What went wrong:
Execution failed for task ':distribution:bwc:bugfix:buildBwcLinuxTar'.
> Building 2.4.1 didn't generate expected file /var/jenkins/workspace/gradle-check/search/distribution/bwc/bugfix/build/bwc/checkout-2.4/distribution/archives/linux-tar/build/distributions/opensearch-min-2.4.1-SNAPSHOT-linux-x64.tar.gz
```

2022-12-15 17:02 UTC, dbwiddis requested changes

2022-12-15 18:19 UTC, ryanbogan commented on server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
> +                inProgressFuture.get(ExtensionsManager.EXTENSION_REQUEST_WAIT_TIMEOUT, TimeUnit.SECONDS);
@dbwiddis I wanted this to still be synchronous for now.  I think we should either raise a PR on feature/extensions that changes all the latches and `.get()` calls or we should wait and do a similar PR once everything is merged to main.  Either way, I think this approach is better than changing them one by one as we merge everything to main.  Thoughts?

2022-12-15 21:36 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
> +                inProgressFuture.get(ExtensionsManager.EXTENSION_REQUEST_WAIT_TIMEOUT, TimeUnit.SECONDS);
Fair, raise an issue, add a TODO comment and we can merge this.

2022-12-16 00:11 UTC, owaiskazi19 commented on server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
> +                inProgressFuture.get(ExtensionsManager.EXTENSION_REQUEST_WAIT_TIMEOUT, TimeUnit.SECONDS);
@ryanbogan can you link the issue here?

2022-12-16 17:26 UTC, ryanbogan commented on server/src/main/java/org/opensearch/extensions/rest/RestSendToExtensionAction.java
> +                inProgressFuture.get(ExtensionsManager.EXTENSION_REQUEST_WAIT_TIMEOUT, TimeUnit.SECONDS);
https://github.com/opensearch-project/OpenSearch/issues/5595

2022-12-16 18:49 UTC, owaiskazi19 approved these changes

2022-12-19 17:52 UTC, merged