[Weighted Routing] Deprecate GET local node weight
opensearch-project/OpenSearch pull request #5680
Opened 2023-01-03 11:36 UTC by anshu1106

Signed-off-by: Anshu Agarwal <anshukag@amazon.com>

### Description
[Describe what this change achieves]

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-04 13:18 UTC, gbbafna commented
I think we should let this functionality be as is . A local collector could use this to find out weights in a light weight manner , which otherwise  would be  heavy to go to the cluster manager.

2023-01-04 13:28 UTC, Bukhtawar commented
> I think we should let this functionality be as is . A local collector could use this to find out weights in a light weight manner , which otherwise would be heavy to go to the cluster manager.

@anshu1106 can correct me but this doesn't remove `_local` query but removes local_weight since it doesn't add much value as weights are relative. The caller is responsible to select specific weights based on the awareness attribute

2023-01-04 13:35 UTC, gbbafna commented
> > I think we should let this functionality be as is . A local collector could use this to find out weights in a light weight manner , which otherwise would be heavy to go to the cluster manager.
> 
> @anshu1106 can correct me but this doesn't remove `_local` query but removes local_weight since it doesn't add much value as weights are relative. The caller is responsible to select specific weights based on the awareness attribute

Got it. My bad, i misread the title  .

2023-01-04 13:49 UTC, gbbafna requested changes

2023-01-04 13:49 UTC, gbbafna commented on server/src/internalClusterTest/java/org/opensearch/cluster/routing/WeightedRoutingIT.java
> -        assertEquals("1.0", weightedRoutingResponse.getLocalNodeWeight());
add `discovered_cluster_manager` assertion as well .

2023-01-04 13:49 UTC, gbbafna commented on server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/ClusterGetWeightedRoutingResponse.java
> +    public Boolean getDiscoveredMaster() {
lets use `cluster_manager` everywhere . `master` is going to get deprecated in 3.0.

2023-01-05 06:54 UTC, gbbafna approved these changes

2023-01-07 17:05 UTC, Bukhtawar commented on server/src/main/java/org/opensearch/action/admin/cluster/shards/routing/weighted/get/ClusterGetWeightedRoutingResponse.java
>      }
There is no explicit need to set them null

2023-01-07 17:07 UTC, Bukhtawar approved these changes

2023-01-07 17:09 UTC, merged