[Feature/Identity] Rest APIs for CRUD actions Internal users
opensearch-project/OpenSearch pull request #5826
Opened 2023-01-11 06:46 UTC by DarshitChanpura

P.S: this PR is based off of https://github.com/opensearch-project/OpenSearch/pull/5613. I will keep rebasing with it till it is merged.

### Description
Sets up base for REST API architecture for identity project

### Issues Resolved
TBD

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-12 18:49 UTC, cwperks reviewed
Thank you @DarshitChanpura, this provides a good base to build upon. I think we should reduce code down to core elements where we can to minimize the change and create an issue to specify testing scenarios to build test cases on for updating a user via the API.

2023-01-12 18:49 UTC, cwperks commented on sandbox/libs/authn/src/main/java/org/opensearch/authn/User.java
> +    public String getHash() {
Why not rename the other methods `getBcryptHash` and `setBcryptHash` to `getHash` and `setHash` respectively?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/build.gradle
> +  implementation 'com.google.guava:guava:31.1-jre'
Guava is a forbidden API in opensearch: https://github.com/opensearch-project/OpenSearch/blob/main/gradle/forbidden-dependencies.gradle#L15-L17

Alternative data structures should be used. I'm not quite sure of the suggested replacements for ImmutableSet and ImmutableList.

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/configuration/Hideable.java
> +public interface Hideable {
Let's add these only when needed. There is no concept of hidden or reserved at the moment.

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/configuration/SecurityDynamicConfiguration.java
> +    public void removeHidden() {
Similar to above, do we need these `removeHidden` and `removeStatic`?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/IdentityAbstractRestApiAction.java
> +            saveAnUpdateConfigs(
nit: `saveAndUpdateConfigs`

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/IdentityAbstractRestApiAction.java
> +        if (existingConfiguration.getSeqNo() < 0) {
What is this block doing?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/IdentityAbstractRestApiAction.java
> +        if (isReadonlyFieldUpdated(existingConfiguration, content)) {
I see that this function currently returns only `false`. How will this eventually be used?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/RestInternalUsersApiAction.java
> +        // TODO: Check role mapping and its validity here
This TODO can be removed

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/RestInternalUsersApiAction.java
> +            badRequestResponse(channel, "Please specify either 'hash' or 'password' when creating a new internal user.");
I think this response should only say `'hash'`, based on line 122 it does not look for a field called `password`.

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/RestApiPrivilegesEvaluator.java
> +        // TODO: implement this in future scope of Identity
👍

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/IdentityAbstractRestApiAction.java
> +        final User user = (User) threadPool.getThreadContext().getTransient(ConfigConstants.IDENTITY_USER);
This is where we will want to use the `Identity.getAuthManager().getSubject()` and abstract this logic out.

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/api/IdentityAbstractRestApiAction.java
> +        final Object originalUser = threadPool.getThreadContext().getTransient(ConfigConstants.IDENTITY_USER);
@peternied Any thoughts on how interactions with ThreadContext should work in the identity module?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/utils/RoutesHelper.java
> +        return addRoutesPrefix(routes, "/_opendistro/_security/api", "/_plugins/_security/api");
These should be changed.

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/utils/RoutesHelper.java
> +    public static List<RestHandler.DeprecatedRoute> addDeprecatedRoutesPrefix(List<RestHandler.DeprecatedRoute> deprecatedRoutes) {
Remove this?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/validation/CredentialsValidator.java
> +        final String regex = this.opensearchSettings.get(ConfigConstants.IDENTITY_RESTAPI_PASSWORD_VALIDATION_REGEX, null);
wdyt about providing a default? Does it make sense to have this be configurable?

2023-01-12 18:49 UTC, cwperks commented on sandbox/modules/identity/src/main/java/org/opensearch/identity/rest/validation/InternalUsersValidator.java
> +        allowedKeys.put("backend_roles", DataType.ARRAY);
Can `backend_roles` and `opendistro_security_roles` be removed here?

2023-01-23 22:31 UTC, peternied requested changes
API actions should not be implemented like this, they should follow the latest convention from OpenSearch, checkout how Delete for Point In Time was [implemented](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20DeletePitAction&type=code) in these places.

There should be a class 'UserService' that knows how to interact with the internal systems to perform these actions and manage state, there is an analog to the [PITService](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/search/PitService.java).  That class would also isolate all configuration updates/propagation, and on this note I would focus this PR on declaring the minimal REST APIs / Service requirements and leave todos around more advanced features like concurrent optmization.

2023-01-24 23:43 UTC, DarshitChanpura commented
> API actions should not be implemented like this, they should follow the latest convention from OpenSearch, checkout how Delete for Point In Time was [implemented](https://github.com/search?q=repo%3Aopensearch-project%2FOpenSearch%20DeletePitAction&type=code) in these places.
> 
> There should be a class 'UserService' that knows how to interact with the internal systems to perform these actions and manage state, there is an analog to the [PITService](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/action/search/PitService.java). That class would also isolate all configuration updates/propagation, and on this note I would focus this PR on declaring the minimal REST APIs / Service requirements and leave todos around more advanced features like concurrent optmization.

As an alternative to this PR, I have created another PR #5990 which leverages the way that core implements REST APIs.

2023-01-31 03:38 UTC, DarshitChanpura commented
Closing this as it is not actively worked on

2023-01-31 03:38 UTC, closed without merging