fixing input validation in segments and delete pit request
opensearch-project/OpenSearch pull request #6645
Opened 2023-03-13 04:22 UTC by bharath-techie

### Description
Before:
If same PIT ID is sent multiple times as part of delete list or pit segments list, then its processed multiple times.

After this change:
Only the unique PIT IDs are sent from rest layer to transport layer

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-13 05:04 UTC, Arpit-Bandejiya approved these changes

2023-03-13 06:38 UTC, ashking94 commented on server/src/main/java/org/opensearch/action/admin/indices/segments/PitSegmentsRequest.java
> +        Set<String> pitIds = new HashSet<>();
nit- shall we rename the local variable to something else?

2023-03-13 06:39 UTC, ashking94 requested changes
can we rename the local pitIds in both the places?

2023-03-13 09:27 UTC, dhruv16dhr approved these changes

2023-05-18 13:54 UTC, Bukhtawar commented on CHANGELOG.md
> +- Avoid negative memory result in IndicesQueryCache stats calculation ([#6917](https://github.com/opensearch-project/OpenSearch/pull/6917))
Is this intentional?

2023-05-23 16:24 UTC, andrross reviewed
What about all the other code paths in both classes where a list or array is passed in and the values are copied into the ArrayList member? No deduplication is happening in those cases that I can see.

2023-05-23 16:24 UTC, andrross commented on CHANGELOG.md
> +- Fixing input validation in segments and delete pit request ([#6645](https://github.com/opensearch-project/OpenSearch/pull/6645))
Please move to the `Unreleased 2.x` section and use the imperative mood ("Fix" instead of "Fixing")

2023-05-23 23:58 UTC, andrross commented
> From REST api perspective , handling here seems to be sufficient. Are other code paths affected via user input ?

It just strikes me as odd that we use lists everywhere, but then in two specific cases a set is used internally to dedupe but ultimately a list is still returned by the `getPitIds()`. I would expect one of two approaches:

- Use a java.util.Set internally in each class to enforce uniqueness in the data structure
- Since JSON cannot express a set type, use java.util.Lists so that the full intent of the JSON request is preserved (namely order and duplicates), but then have the consumer of `getPitIds()` explicitly do the de-duplication

I don't doubt that this fixes the bug, but it doesn't feel like a comprehensive fix that would prevent this from happening again.

2023-05-24 04:06 UTC, bharath-techie commented
> > From REST api perspective , handling here seems to be sufficient. Are other code paths affected via user input ?
> 
> It just strikes me as odd that we use lists everywhere, but then in two specific cases a set is used internally to dedupe but ultimately a list is still returned by the `getPitIds()`. I would expect one of two approaches:
> 
>     * Use a java.util.Set internally in each class to enforce uniqueness in the data structure
> 
>     * Since JSON cannot express a set type, use java.util.Lists so that the full intent of the JSON request is preserved (namely order and duplicates), but then have the consumer of `getPitIds()` explicitly do the de-duplication
> 
> 
> I don't doubt that this fixes the bug, but it doesn't feel like a comprehensive fix that would prevent this from happening again.

Addressed this - made changes in consumer instead - needed to make changes only in transport layer . security plugin handles duplicates already as we form a map of pitids and indices when decoding PITs.

2023-05-24 17:29 UTC, bharath-techie commented on server/src/main/java/org/opensearch/action/admin/indices/segments/TransportPitSegmentsAction.java
> +        request.clearAndSetPitIds(new ArrayList<>(pitIdSet));
there are dependencies in security plugin , so i'm trying to find a solution which doesn't change the class contract if possible.

2023-05-24 17:44 UTC, bharath-techie commented on server/src/main/java/org/opensearch/action/admin/indices/segments/TransportPitSegmentsAction.java
> +        request.clearAndSetPitIds(new ArrayList<>(pitIdSet));
Security plugin already removes duplicates for PIT ID - need to handle only in transport layer, let me know if the new approach works which doesn't mutate the request.

2023-05-24 18:00 UTC, andrross approved these changes

2023-05-25 09:22 UTC, Bukhtawar approved these changes

2023-05-25 09:23 UTC, merged