[Search Profile] Time in seconds in addition to nanoseconds
opensearch-project/OpenSearch pull request #6842
Opened 2023-03-27 15:46 UTC by aswath86

### Description

Currently the profile API responds with only nanoseconds, `time_in_nanos`. When debugging large queries (especially nested and pipeline aggregations) that run for several seconds, with just the `time_in_nanos` information, it quite difficult to make out if a particular aggregator took, for example, 15 seconds OR 1.5 seconds or 0.15 seconds. The number of digits in nanosecond makes it difficult for human eyes, especially when scrolling over 1000s of lines in the `profile` response, for just a single shard.

This may not be a problem for an experienced pair of eye but for new users it could be.

### Issues Resolved

This PR adds a `time_in_seconds` to make it easy on the human eyes to read and digest the information (without having to count the number of digits in the `time_in_nanos`, each time). 

Ideally, a "Search Profile UI" like in the latest versions of Kibana would be the best way to analyse the run time. And the `time_in_seconds` or `time_in_ms` can be calculated from the `nanos` on the UI layer. Until then, should should help. I'm open to making changes based on suggestions.

This is how the response with `time_in_seconds` would look like,

![time_in_seconds](https://user-images.githubusercontent.com/32518356/227992757-e1339192-5625-46dd-a2fb-9f8991928c18.png)

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-03-27 16:59 UTC, andrross commented
> And the time_in_seconds or time_in_ms can be calculated from the nanos on the UI layer. Until then, should should help.

I think you're absolutely right that this is UI concern. However, I don't think adding duplicate information at the service layer is the right way to go. Once it is in the API removing it will be a breaking change and require a deprecate/remove cycle across major versions.

2023-03-27 22:29 UTC, dblock requested changes
+1 on what @andrross said. Generally,  think returning what is effectively a rounded value of another value in the response for visual purposes in an API is an anti-pattern. What if the task takes hours....

Maybe others feel strongly otherwise? If this is to be merged it will need to have tests and documentation, please.

2023-04-04 14:21 UTC, aswath86 commented
Thank you! I have created a Feature Request for a proper UI.

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3779

2023-04-11 20:11 UTC, andrross commented
Closing as I think we're in agreement that the UI is the right place to solve this.

2023-04-11 20:11 UTC, closed without merging