Adding the ExtensionActionUtil class
opensearch-project/OpenSearch pull request #6969
Opened 2023-04-04 05:46 UTC by Kuanysh-kst

### Description
In this PR, I add methods to the ExtensionActionUtil class to reduce code repetition

### Issues Resolved
https://github.com/opensearch-project/opensearch-sdk-java/issues/607

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-04 17:40 UTC, dblock commented
Needs tests please.

2023-04-08 15:55 UTC, Kuanysh-kst commented
@dbwiddis  why when I want to run Junit test I get an error: Caused by: java.io.EOFException: tried to read: 101 bytes but this stream is limited to: 7
This error occurs when I need to create a new Extension Action Request object in this line:
```
   actionRequest = (ActionRequest) constructor.newInstance(requestByteStream);
```
and as I understood that the error occurs when comparing the length of a new byte array and the unicode of the first byte
here is the error path:
```
Caused by: java.io.EOFException: tried to read: 101 bytes but this stream is limited to: 7
	at org.opensearch.common.io.stream.InputStreamStreamInput.ensureCanReadBytes(InputStreamStreamInput.java:137)
	at org.opensearch.common.io.stream.StreamInput.readArraySize(StreamInput.java:1310)
	at org.opensearch.common.io.stream.StreamInput.readString(StreamInput.java:420)
	at org.opensearch.tasks.TaskId.readFromStream(TaskId.java:96)
	at org.opensearch.transport.TransportRequest.<init>(TransportRequest.java:71)
	at org.opensearch.action.ActionRequest.<init>(ActionRequest.java:56)
	at org.opensearch.extensions.action.ExtensionActionRequest.<init>(ExtensionActionRequest.java:52)
```
here is a test version of the test that throws an error:
```
            @Test
            public void testCreateActionRequest() throws IOException {
            String action = "example";
            ExtensionActionRequest request = new ExtensionActionRequest(action, action.getBytes(StandardCharsets.UTF_8));

            byte[] array = ExtensionActionUtil.createProxyRequestBytes(request);
            ExtensionActionRequest request1 = new ExtensionActionRequest(action,array);

            ActionRequest actionRequest = ExtensionActionUtil.createActionRequest(request1);
            assertNotNull(actionRequest);

    }
```

2023-04-09 16:26 UTC, Kuanysh-kst commented
I solved it by adding this code to test:
```
        String action = "abc" ;
        int length = 10;
        byte lengthByte = (byte) (length & 0xff);

        byte[] requestClass = ExtensionActionRequest.class.getName().getBytes();
        System.out.println("cl: "+requestClass.length+ "+1+"+action.getBytes().length);
        byte[] result = ByteBuffer.allocate(requestClass.length + 2 + action.codePointAt(0))
            .put(requestClass)
            .put(UNIT_SEPARATOR)
            .put(lengthByte)
            .put(action.getBytes(StandardCharsets.UTF_8))
            .array();
```
with this code I set the length for the byte array:
`  byte lengthByte = (byte) (length & 0xff);`

2023-04-12 16:49 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    private static int delimPos(byte[] bytes) {
Let's make this `public`.

2023-04-12 16:49 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +        int nullPos = delimPos(requestBytes.getRequestBytes());
```suggestion
        int delimlPos = delimPos(requestBytes.getRequestBytes());
```

2023-04-12 16:49 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +     */
add `@param` and `@return` javadocs.  In the return make sure you indicate the possibility that it can be null.

2023-04-12 16:49 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static ExtensionActionRequest createExtensionActionRequest(ActionRequest actionRequest) {
you aren't doing anything with `actionRequest` here.  I'm not sure what this method is supposed to do.

See comment here: https://github.com/opensearch-project/opensearch-sdk-java/issues/607#issuecomment-1503811006

You want to replicate (at least some of) the code from the method `private static <T extends Writeable> byte[] convertParamsToBytes(T actionParams)` in https://github.com/opensearch-project/job-scheduler/pull/349.  Also look at the SDK HelloWorld RestRemoteHelloAction here: https://github.com/opensearch-project/opensearch-sdk-java/blob/main/src/main/java/org/opensearch/sdk/sample/helloworld/rest/RestRemoteHelloAction.java

Try to find the common parts of that code and the Job-Scheduler PR above and make that a method.

2023-04-26 16:50 UTC, dbwiddis requested changes
See comments on the issue

2023-04-26 16:50 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static int delimPos(byte[] bytes) {
Needs javadoc since it is public.

2023-04-26 16:50 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        assertNotNull(extensionActionRequest);
We should be able to test the getters on this object with an assertion.
```java
assertEquals( ..., extensionActionRequest.getAction());
assertEquals( ..., extensionActionRequest.getRequestBytes());
```

2023-04-26 16:50 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static ActionRequest createActionRequest(ExtensionActionRequest requestBytes) {
and then change all the `requestBytes.getRequestBytes()` to just `requestBytes`.

2023-04-26 16:50 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +     * @param request r is an object of the "Remote Extension Action Request" class, containing information about the
```suggestion
     * @param request an instance of a request extending {@link ActionRequest}, containing information about the
```

2023-04-26 16:50 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        byte[] requestClass = ExtensionActionRequest.class.getName().getBytes();
```suggestion
        byte[] requestClass = ExtensionActionRequest.class.getName().getBytes(StandardCharsets.UTF_8);
```

2023-04-26 16:50 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        byte[] result = ByteBuffer.allocate(requestClass.length + 1 + action.codePointAt(0))
I think this should be `requestBytes.length` here?

2023-04-26 16:50 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static byte[] createProxyRequestBytes(ExtensionActionRequest request) {
```suggestion
    public static byte[] createProxyRequestBytes(ActionRequest request) {
```

2023-04-26 16:50 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +        return ByteBuffer.allocate(requestClassBytes.length + 1 + request.getRequestBytes().length)
rather than request.getRequestBytes() here, you need to do the streamoutput collection of the request using writeTo() here.

2023-05-03 16:51 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        assertNotNull(extensionActionRequest);
can we test more than just not null?  the `ExtensionActionRequest` probably has some getters that you can test equality with what you expect.

2023-05-10 16:27 UTC, dbwiddis requested changes
Looking good! Some final cleanup and a few missing tests.

2023-05-10 16:27 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +        } catch (Exception e) {
change to `throws ReflectiveOperationException`

2023-05-10 16:27 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static <T extends Writeable> byte[] convertParamsToBytes(T actionParams) throws IOException {
I don't particulary like `actionParams` as the variable name. This is a writeable class instance, so maybe `writeableObject`?

2023-05-10 16:27 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +
I only see 3 test methods but there are 5 methods in the class you are testing. If one of these test methods is testing more than one, please add comments indicating which ones it is testing.

2023-05-10 16:27 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        assertNotNull(actionRequest);
This `assertNotNull` is really just a fallback if there is no way to test anything else, but in this case we are creating an `ActionRequest` object which extends `TransportRequest`.   We can try to find something to test.

In this case we can test getting the parent task ID returns `TaskId.EMPTY_TASK_ID` and `getShouldStoreResult()` should be false.

2023-05-10 16:27 UTC, dbwiddis requested changes
Looking good! Some final cleanup and a few missing tests.

2023-05-17 16:25 UTC, dbwiddis requested changes
Some other changes have caused compilation failures, please rebase to main and update.

2023-05-17 16:25 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +        } catch (Exception e) {
Since `convertParamsToBytes()` no longer throws an exception you can remove this catch clause.

2023-05-17 16:25 UTC, dbwiddis commented on server/src/test/java/org/opensearch/extensions/action/ExtensionActionUtilTest.java
> +        byte[] bytes = extensionActionRequest.getRequestBytes();
After a recent change to use protobuf, this is no longer a `byte[]`, it is a `ByteString`. Use `toByteArray()` to convert it to bytes (you may have to do this multiple times in this test class).

2023-05-24 16:52 UTC, dbwiddis requested changes
Almost there!
1. Remove unneeded method and test
2. For exceptions either:   throw checked exceptions to user (try to wrap/chain off the earlier exception, like `catch ReflectiveOperationException roe) { throw new IllegalArgumentException("Could not instantiate class", roe);`; or throw illegal state exceptions for "this should never happen" types.
3. Try to avoid confusing names in example classes
4. Avoid duplicating "test" in method names.

2023-05-24 16:52 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +    public static ExtensionActionRequest createExtensionActionRequestFromBytes(byte[] bytes) {
I don't think we need this method at all, just delete it. :)

2023-05-24 16:58 UTC, dbwiddis commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +            logger.error("ReflectiveOperationException occurred while creating extensionAction request from bytes: " + e.getMessage());
Or, you can just throw the ReflectiveOperationException directly if it's the only type thrown, no need to catch and rethrow a different type.

2023-05-30 06:41 UTC, Kuanysh-kst commented on server/src/main/java/org/opensearch/extensions/action/ExtensionActionUtil.java
> +            logger.error("ReflectiveOperationException occurred while creating extensionAction request from bytes: " + e.getMessage());
@dbwiddis can you check the new commit

2023-06-04 14:38 UTC, Kuanysh-kst commented
@owaiskazi19 , @ryanbogan  can you check this PR

2023-06-10 19:10 UTC, dbwiddis approved these changes
LGTM

2023-06-21 16:09 UTC, ryanbogan approved these changes

2023-06-21 17:08 UTC, dbwiddis commented
Gradle check failure is a bwc bug since fixed. Please rebase to main to get gradle check to pass.

2023-06-21 19:23 UTC, merged