Contributing update review tips
opensearch-project/OpenSearch pull request #7107
Opened 2023-04-11 20:07 UTC by acarbonetto

### Description
Update contributing page to include tips/tricks to help developers get their PRs into an approved state (as discussed here: https://opensearch.slack.com/archives/C038PDJ14JZ/p1681232261749639?thread_ts=1681231289.117129&cid=C038PDJ14JZ)

### Issues Resolved
none

### Check List
- [N/A] New functionality includes testing.
  - [N/A] All tests pass
- [N/A] New functionality has been documented.
  - [N/A] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [N/A] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-04-13 21:32 UTC, dblock requested changes
I like it. I think the ES mention needs fixing because it's incorrect.

2023-04-13 21:32 UTC, dblock commented on CONTRIBUTING.md
> +2. *Do not copy ES code*: SSPL co-mingling will get rejected real fast.
This is incorrect. 

You're not allowed to look at/copy non-APLv2 compatible code, which includes SSPL. You are actually allowed to copy code from ES < 7.10.2 which was APLv2 for example.

So let's stay out of calling out ES explicitly and replace this with something like ensure that code is APLv2 compatible and confirm that you have not copied any code that's not compatible if it implements a feature that may or may not exist in another product?

2023-04-13 21:32 UTC, dblock commented on CONTRIBUTING.md
> +7. *test, test, test*: pretty self explanatory ([OpenSearchTestCase](./test/framework/src/main/java/org/opensearch/test/OpenSearchTestCase.java) for unit tests, [OpenSearchIntegTestCase](./test/frame
Nit: Get rid of spaces before/after `/` to make it consistent with other text. Same for `w/`?

2023-04-19 15:17 UTC, dblock reviewed
Should this be in https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md actually?

2023-04-20 18:54 UTC, dblock commented
@acarbonetto Yeah I think that would be best because we copy CONTRIBUTING.md for general high level stuff across all repos. You'll get it read more often if it's int he developer guide. Sorry to create more work for you!

2023-09-14 18:43 UTC, kotwanikunal commented
Apologies. This PR was auto closed without reaching a resolution from the maintainers.
Re-opening to move it forward.
Thanks for your contributions to OpenSearch!

2023-10-30 11:04 UTC, BhumikaSaini-Amazon commented on CONTRIBUTING.md
> +1. *Minimize BWC guarantees*: First PR review heavily focuses on the public facing API. This is what we have to "guarantee" as non-breaking for bwc across major versions.
We should also link https://github.com/opensearch-project/OpenSearch/blob/main/DEVELOPER_GUIDE.md#backwards-compatibility here for details on this front

2023-10-30 11:04 UTC, BhumikaSaini-Amazon commented on CONTRIBUTING.md
> +If you're bias towards liberal guardrails, you have a higher chance of the PR getting merged quickly. We can always relax these guard rails in smaller followup PRs. Reverting a GA feature is much mor
> If you're bias towards liberal guardrails ...

Should this be "If you are biased towards restrictive guardrails ..." instead?

2024-01-08 17:29 UTC, acarbonetto commented
> Hi @acarbonetto, Is this being worked upon? Feel free to reach out to maintainers for further reviews.

Hi @ticheng-aws - sorry I've been off project for a while.  I'll take a look in day or two if nobody else does.

2024-03-29 20:42 UTC, scrawfor99 commented
I opened a PR to get this over the finish line. Thanks for all the work @acarbonetto. At this point we can close this. @peternied could you help there? Thanks

2024-03-29 21:51 UTC, closed without merging

2024-03-29 21:51 UTC, kotwanikunal commented
I can close this one @scrawfor99! Please refer to #12981 for further updates.