Add support to run SegRep integ tests using remote store settings
opensearch-project/OpenSearch pull request #7361
Opened 2023-05-02 07:02 UTC by sachinpkale

### Description
- We want to test various scenarios involving replica promotion, peer recovery, index close and re-open with remote store.
- These scenarios are already being tested in various [integ tests](https://github.com/opensearch-project/OpenSearch/tree/main/server/src/internalClusterTest/java/org/opensearch/indices/replication) of Segment Replication.
- In this change, we re-use the same tests by enabling remote store settings.

### Related Issues
- - https://github.com/opensearch-project/OpenSearch/issues/6195
- 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-05-02 07:47 UTC, sachinpkale commented
Checking build failure.

2023-05-02 07:59 UTC, sachinpkale commented
Build is failing due to flaky test mentioned here: https://github.com/opensearch-project/OpenSearch/issues/7327

2023-05-04 11:11 UTC, gbbafna approved these changes

2023-05-04 12:56 UTC, ashking94 commented on server/src/internalClusterTest/java/org/opensearch/remotestore/SegmentReplicationRemoteStoreIT.java
> +public class SegmentReplicationRemoteStoreIT extends SegmentReplicationIT {
can we add a note that this test would run all the tests in SegmentReplicationIT but with overriding the indexSettings(), feature flags and setup part.

2023-05-04 13:29 UTC, ashking94 commented on server/src/main/java/org/opensearch/index/shard/IndexShard.java
> +            }
can we extract this to a method - i see 2 separate occurrences in this files atleast. If there are more, we can just hit a method rather duplicating code.

2023-05-04 13:31 UTC, ashking94 requested changes
minor comments, lgtm otherwise.

2023-05-05 05:26 UTC, ashking94 approved these changes
looks good

2023-05-05 06:09 UTC, merged