Resolve #7228
opensearch-project/OpenSearch pull request #7953
Opened 2023-06-07 15:35 UTC by BhumikaSaini-Amazon

### Description
Resolves #7228 

### Related Issues
Resolves #7228

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-08 06:53 UTC, linuxpi commented on server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferManager.java
> +        byte[] metadataBytes;
can we extract a method out of this new code snippet and use in the test as well?

2023-06-08 06:56 UTC, linuxpi commented
Changes look good @BhumikaSaini-Amazon. Please check why the tests are failing

2023-06-08 12:08 UTC, linuxpi requested changes

2023-06-08 12:23 UTC, BhumikaSaini-Amazon commented
The following failed tests have been reported as flaky:
1. `org.opensearch.remotestore.RemoteStoreRefreshListenerIT.testRemoteRefreshRetryOnFailure` - #7703 (we may need to reopen this)
2. `org.opensearch.cluster.allocation.AwarenessAllocationIT.testThreeZoneOneReplicaWithForceZoneValueAndLoadAwareness` - #3603

The following failed tests unrelated with the PR changes passed on CI rerun:
1. `org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu`
2. `org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase`

Will report these 2 as flaky.

2023-06-08 12:25 UTC, linuxpi approved these changes

2023-06-09 04:39 UTC, BhumikaSaini-Amazon commented
References for the new flaky tests:
1. `org.opensearch.search.backpressure.SearchBackpressureIT.testSearchShardTaskCancellationWithHighCpu` - #7972
2. `org.opensearch.http.SearchRestCancellationIT.testAutomaticCancellationMultiSearchDuringFetchPhase` - #7980

2023-06-12 08:47 UTC, gbbafna commented on server/src/main/java/org/opensearch/index/translog/transfer/TranslogTransferMetadata.java
> +    public static final String METADATA_CODEC = "md";
No need for them to be public. Lets make them package private .

2023-06-12 08:48 UTC, gbbafna reviewed
LGTM. 1 minor comment

2023-06-12 12:10 UTC, BhumikaSaini-Amazon commented
Failing tests in build:
```
org.opensearch.cluster.shards.ClusterShardLimitIT.testCreateIndexWithMaxClusterShardSetting
```

Flaky test #6287

2023-06-12 13:16 UTC, gbbafna approved these changes

2023-06-13 05:26 UTC, merged