Cat Nodes API with Protobuf
opensearch-project/OpenSearch pull request #9097
Opened 2023-08-03 19:04 UTC by VachaShah

### Description
The purpose of this draft PR is to create a new cat nodes API with protobuf as a serialization/de-serialization mechanism for node-to-node communication. We also benchmark the performance results in comparison to the original cat nodes API. This PR creates a separate path for the new API but when these changes are to be merged, a lot of code in the original API can be replaced with the newer approach. For the purpose of this POC, as of now the files are separate.

### Related Issues
#6844
#1287

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff
- [ ] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-08-14 09:16 UTC, gashutos commented
Strictly speaking from performance dimension,
I was just benchmarkin netty http layer for `search` path. We hardly spend `1 or 2 ms` in netty layer per request. 
Any benchmark available for protobuf ?

2023-10-02 20:55 UTC, dblock commented
@VachaShah Given https://github.com/opensearch-project/OpenSearch/issues/6844#issuecomment-1742250229, do you have any ideas about how to bring this into OpenSearch as maybe an experimental feature? What are next steps?

2023-10-02 23:12 UTC, VachaShah commented
> @VachaShah Given [#6844 (comment)](https://github.com/opensearch-project/OpenSearch/issues/6844#issuecomment-1742250229), do you have any ideas about how to bring this into OpenSearch as maybe an experimental feature? What are next steps?

I am working on getting the changes from the POC in #9097 to merge in the repo. We are also working on getting the numbers for APIs like search.

2023-10-12 17:58 UTC, peternied requested changes
This is really exciting work - thanks for getting this out there.

> For the purpose of this POC, as of now the files are separate.

What our your thoughts on the end state for this change?  I'm resistant to merge so much duplicate code.

2023-10-12 17:58 UTC, peternied commented on libs/core/src/main/java/org/opensearch/core/common/io/stream/ProtobufWriteable.java
> +        void write(OutputStream out, V value) throws IOException;
Its strange than the writer is via an OutputStream, but the reader isn't a symetrical version that uses InputStream.  Can we align the types to be consistant, be it bytes[] or *Stream?

2023-10-12 17:58 UTC, peternied commented on server/src/main/java/org/opensearch/tasks/ProtobufTask.java
> +public class ProtobufTask {
This class is nearly identical to the existing Task, why do we need a largely identical protobuf version? This seems to imply there is coupling between the existing OpenSearch data models and their serialized form.  Can we decompose these relationships more?

2023-10-12 17:58 UTC, peternied reviewed
~ Duplicate comment ~

2023-10-12 18:42 UTC, VachaShah commented
> This is really exciting work - thanks for getting this out there.
> 
> > For the purpose of this POC, as of now the files are separate.
> 
> What our your thoughts on the end state for this change? I'm resistant to merge so much duplicate code.

Hi @peternied, thank you for your comments! This PR is not be merged, its a draft PR for the work done to get numbers for which I created a parallel API _cat/nodes_protobuf to compare with the original version. The changes to be merged will go in incremental PRs, which I will raise later. This PR is just out here in the draft state for the work done for the POC.

2023-10-12 18:44 UTC, VachaShah commented
> > This is really exciting work - thanks for getting this out there.
> > > For the purpose of this POC, as of now the files are separate.
> > 
> > 
> > What our your thoughts on the end state for this change? I'm resistant to merge so much duplicate code.
> 
> Hi @peternied, thank you for your comments! This PR is not be merged, its a draft PR for the work done to get numbers for which I created a parallel API _cat/nodes_protobuf to compare with the original version. The changes to be merged will go in incremental PRs, which I will raise later. This PR is just out here in the draft state for the work done for the POC.

I think I was not clear in the description of the PR, so I added a comment about this as well.

2023-10-13 19:10 UTC, dblock commented
Any parts of this PR that _can_ be merged? Otherwise I think we can document this in https://github.com/opensearch-project/OpenSearch/issues/6844 and close it?

2023-10-17 18:09 UTC, VachaShah commented
> Any parts of this PR that _can_ be merged? Otherwise I think we can document this in #6844 and close it? (And nice work!)

Thank you @dblock! I will raise incremental PRs for this, so closing this one now. I will make sure to update #6844 to document this.

2023-10-17 18:09 UTC, closed without merging