Rank feature - unknown field linear
opensearch-project/OpenSearch pull request #983
Opened 2021-07-18 23:40 UTC by Hronom

### Description
Add support for rank feature query linear
 
### Issues Resolved
https://github.com/opensearch-project/OpenSearch/issues/977
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-07-22 05:38 UTC, setiah commented
start gradle check

2021-07-22 14:16 UTC, dblock approved these changes

2021-07-22 14:19 UTC, dblock commented
Much thanks!

@nknize Care to double check for me that this looks right?

@Hronom We need to document this - care to PR or open an issue in https://github.com/opensearch-project/documentation-website please?

2021-07-22 14:20 UTC, dblock commented
@Hronom How do you feel about adding a REST API-level test for this that matches what you described in #977?

2021-07-22 17:58 UTC, dblock requested changes
I clicked approve too fast, I'll get back to this.

2021-07-23 00:13 UTC, Hronom commented
@dblock I will try to put some docs on weekends

2021-07-23 00:16 UTC, Hronom commented
@dblock I pretty new in this project, can you help me:
> @Hronom How do you feel about adding a REST API-level test for this that matches what you described in #977?
Where is this REST API-level tests? Please point me to the class or example of it. I added tests for this feature, but not sure is they API level or not...

2021-07-24 19:17 UTC, Hronom commented
@dblock added docs https://github.com/opensearch-project/documentation-website/pull/114

2021-07-25 15:59 UTC, Hronom commented
start gradle check

2021-07-26 13:33 UTC, dblock commented
I didn't forget about this, please bear with me. I need to do some homework before this can be merged, related to the fork.

2021-07-28 22:31 UTC, dblock commented
@Hronom Thank you for your contribution! This PR looks very similar to [elasticsearch#67438](https://github.com/elastic/elasticsearch/pull/67438) and [elasticsearch#67670](https://github.com/elastic/elasticsearch/pull/67670). Was your code based off either of those PRs, or was it based on the current master of elasticsearch?

2021-07-28 22:49 UTC, Hronom commented
@dblock It's based on that PR's, also it use function provided by core Lucene.

2021-07-28 23:12 UTC, Hronom commented
Added fix in exception message for supported functions

2021-07-28 23:21 UTC, Hronom commented
start gradle check

2021-07-29 16:55 UTC, dblock commented
start gradle check

2021-07-29 18:28 UTC, dblock approved these changes

2021-07-29 18:28 UTC, merged

2021-07-29 18:29 UTC, dblock commented
Merged, thank you @Hronom. I imagine we want this in 1.1. Could you please open a backport PR into that branch? Thank you.

2021-07-29 23:38 UTC, Hronom commented
@dblock created https://github.com/opensearch-project/OpenSearch/pull/1025