Add support for query profiler with concurrent aggregation (#9248)
opensearch-project/OpenSearch pull request #9835
Opened 2023-09-06 17:43 UTC by ticheng-aws

(cherry picked from commit https://github.com/opensearch-project/OpenSearch/commit/a7374460aa0e91b5af4859458e771e5b2525b9e2)

### Description
At present, the query profiler is the total timing obtained by summing all segments. However, this does not accurately represent the detailed timing of the query, including queue time and gap time, during concurrent execution. This PR will address the problem.

### Related Issues
Resolves https://github.com/opensearch-project/OpenSearch/issues/8330 https://github.com/opensearch-project/OpenSearch/issues/7354

### Check List
- [X] New functionality includes testing.
  - [X] All tests pass
- [X] New functionality has been documented.
  - [X] New functionality has javadoc added
- [X] Commits are signed per the DCO using --signoff
- [X] Commit changes are listed out in CHANGELOG.md file (See: [Changelog](../blob/main/CONTRIBUTING.md#changelog))

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-09-06 19:20 UTC, reta approved these changes

2023-09-06 20:23 UTC, reta requested changes
@sohami @ticheng-aws preventing the merge, we have NPE here https://github.com/opensearch-project/OpenSearch/issues/9815 and another NPE variation in this pull request, we cannot let it sneak into  the release:

```
java.lang.NullPointerException: Cannot invoke "org.opensearch.action.search.SearchResponse.getFailedShards()" because "profileResponse" is null
	at __randomizedtesting.SeedInfo.seed([E68DEFD659967F87:B55838D408DE9DFB]:0)
	at org.opensearch.search.profile.query.QueryProfilerIT.testProfileMatchesRegular(QueryProfilerIT.java:195)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
```

2023-09-06 22:34 UTC, sohami commented
> > @sohami @ticheng-aws holding the merge, we have NPE here #9815 and another NPE variation in this pull request, we cannot let it sneak into the release:
> > ```
> > java.lang.NullPointerException: Cannot invoke "org.opensearch.action.search.SearchResponse.getFailedShards()" because "profileResponse" is null
> > 	at __randomizedtesting.SeedInfo.seed([E68DEFD659967F87:B55838D408DE9DFB]:0)
> > 	at org.opensearch.search.profile.query.QueryProfilerIT.testProfileMatchesRegular(QueryProfilerIT.java:195)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> > 	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1750)
> > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:938)
> > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:974)
> > 	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:988)
> > 	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
> > ```
> 
> @reta We looked into [this bug](https://github.com/opensearch-project/OpenSearch/issues/9787). The NPE is happening because of an issue observed in concurrent search path of profile where rewrite is happening during execution phase as well (this use case was unknown). This issue existed even before these new changes were done but it is showing up now since we enabled the `QueryProfilerIT` with concurrent search flag enabled as part of these changes. So the plan is to merge these new profile changes and disable the failing test for concurrent segment search for now. The fix will be worked on as part of the issue you created and we will enable the test with that fix. Given only some specific queries (with profile option enabled) in concurrent segment search path is impacted and is behind experimental flag, we should still be fine back porting this PR for experimental release in 2.10.0. Wdyt ?

Just realized [this](https://github.com/opensearch-project/OpenSearch/issues/9815) is a separate issue and is happening in the new code path. We will not back-port the new changes to 2.10 in that case.

2024-01-06 00:25 UTC, ticheng-aws commented
Closd this PR as it's been backported from https://github.com/opensearch-project/OpenSearch/pull/10898.

2024-01-06 00:25 UTC, closed without merging